// source: google/protobuf/api.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

import jspb from "google-protobuf";
import {SourceContext} from "google-protobuf/google/protobuf/source_context_pb.mjs"; // proto import: "google/protobuf/source_context.proto"
import {Type, Field, Enum, EnumValue, Option, Syntax} from "google-protobuf/google/protobuf/type_pb.mjs"; // proto import: "google/protobuf/type.proto"

/**
 * ES6 class generated by js_generator.cc.
 *
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
export class Api extends jspb.Message {
  /**
   * Generated by JsPbCodeGenerator.
   * @param {Array=} opt_data Optional initial data array, typically from a
   * server response, or constructed directly in Javascript. The array is used
   * in place and becomes part of the constructed object. It is not cloned.
   * If no data is provided, the constructed object will be empty, but still
   * valid.
   * @extends {jspb.Message}
   * @constructor
   */
  constructor(opt_data) {
    super(...arguments);
    jspb.Message.initialize(this, opt_data, 0, -1, Api.repeatedFields_, null);
  }

  /**
   * List of repeated fields within this message type.
   * @private {!Array<number>}
   * @const
   */
  static repeatedFields_ = [2,3,6];



  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  toObject(opt_includeInstance) {
    return Api.toObject(opt_includeInstance, this);
  }


  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!Api} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  static toObject(includeInstance, msg) {
    var f, obj = {
  name: jspb.Message.getFieldWithDefault(msg, 1, ""),
  methodsList: jspb.Message.toObjectList(msg.getMethodsList(),
      Method.toObject, includeInstance),
  optionsList: jspb.Message.toObjectList(msg.getOptionsList(),
      Option.toObject, includeInstance),
  version: jspb.Message.getFieldWithDefault(msg, 4, ""),
  sourceContext: (f = msg.getSourceContext()) && SourceContext.toObject(includeInstance, f),
  mixinsList: jspb.Message.toObjectList(msg.getMixinsList(),
      Mixin.toObject, includeInstance),
  syntax: jspb.Message.getFieldWithDefault(msg, 7, 0),
  edition: jspb.Message.getFieldWithDefault(msg, 8, "")
    };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  }


  /**
   * Deserializes binary data (in protobuf wire format).
   * @param {jspb.binary.bytesource.ByteSource} bytes The bytes to deserialize.
   * @return {!Api}
   */
  static deserializeBinary(bytes) {
    var reader = new jspb.BinaryReader(bytes);
    var msg = new Api;
    return Api.deserializeBinaryFromReader(msg, reader);
  }


  /**
   * Deserializes binary data (in protobuf wire format) from the
   * given reader into the given message object.
   * @param {!Api} msg The message object to deserialize into.
   * @param {!jspb.BinaryReader} reader The BinaryReader to use.
   * @return {!Api}
   */
  static deserializeBinaryFromReader(msg, reader) {
    while (reader.nextField()) {
      if (reader.isEndGroup()) {
        break;
      }
      var field = reader.getFieldNumber();
      switch (field) {
      case 1:
        var value = /** @type {string} */ (reader.readStringRequireUtf8());
        msg.setName(value);
        break;
      case 2:
        var value = new Method;
        reader.readMessage(value,Method.deserializeBinaryFromReader);
        msg.addMethods(value);
        break;
      case 3:
        var value = new Option;
        reader.readMessage(value,Option.deserializeBinaryFromReader);
        msg.addOptions(value);
        break;
      case 4:
        var value = /** @type {string} */ (reader.readStringRequireUtf8());
        msg.setVersion(value);
        break;
      case 5:
        var value = new SourceContext;
        reader.readMessage(value,SourceContext.deserializeBinaryFromReader);
        msg.setSourceContext(value);
        break;
      case 6:
        var value = new Mixin;
        reader.readMessage(value,Mixin.deserializeBinaryFromReader);
        msg.addMixins(value);
        break;
      case 7:
        var value = /** @type {!proto.google.protobuf.Syntax} */ (reader.readEnum());
        msg.setSyntax(value);
        break;
      case 8:
        var value = /** @type {string} */ (reader.readStringRequireUtf8());
        msg.setEdition(value);
        break;
      default:
        reader.skipField();
        break;
      }
    }
    return msg;
  }


  /**
   * Serializes the message to binary data (in protobuf wire format).
   * @return {!Uint8Array}
   */
  serializeBinary() {
    var writer = new jspb.BinaryWriter();
    this.constructor.serializeBinaryToWriter(this, writer);
    return writer.getResultBuffer();
  }


  /**
   * Serializes the given message to binary data (in protobuf wire
   * format), writing to the given BinaryWriter.
   * @param {!Api} message
   * @param {!jspb.BinaryWriter} writer
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  static serializeBinaryToWriter(message, writer) {
    var f = undefined;
    f = message.getName();
    if (f.length > 0) {
      writer.writeString(
        1,
        f
      );
    }
    f = message.getMethodsList();
    if (f.length > 0) {
      writer.writeRepeatedMessage(
        2,
        f,
        Method.serializeBinaryToWriter
      );
    }
    f = message.getOptionsList();
    if (f.length > 0) {
      writer.writeRepeatedMessage(
        3,
        f,
        Option.serializeBinaryToWriter
      );
    }
    f = message.getVersion();
    if (f.length > 0) {
      writer.writeString(
        4,
        f
      );
    }
    f = message.getSourceContext();
    if (f != null) {
      writer.writeMessage(
        5,
        f,
        SourceContext.serializeBinaryToWriter
      );
    }
    f = message.getMixinsList();
    if (f.length > 0) {
      writer.writeRepeatedMessage(
        6,
        f,
        Mixin.serializeBinaryToWriter
      );
    }
    f = message.getSyntax();
    if (f !== 0.0) {
      writer.writeEnum(
        7,
        f
      );
    }
    f = message.getEdition();
    if (f.length > 0) {
      writer.writeString(
        8,
        f
      );
    }
  }


  /**
   * optional string name = 1;
   * @return {string}
   */
  getName() {
    return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
  }

  /**
   * @param {string} value
   * @return {!proto.google.protobuf.Api} returns this
   */
  setName(value) {
    return jspb.Message.setProto3StringField(this, 1, value);
  }

  /**
   * repeated Method methods = 2;
   * @return {!Array<!proto.google.protobuf.Method>}
   */
  getMethodsList() {
    return /** @type{!Array<!proto.google.protobuf.Method>} */ (
      jspb.Message.getRepeatedWrapperField(this, Method, 2));
  }


  /**
   * @param {!Array<!proto.google.protobuf.Method>} value
   * @return {!proto.google.protobuf.Api} returns this
  */
  setMethodsList(value) {
    return jspb.Message.setRepeatedWrapperField(this, 2, value);
  }


  /**
   * Adds a value to the repeated field fieldName 
   *
   * @param {!proto.google.protobuf.Method=} opt_value
   * @param {number=} opt_index
   * @return {!proto.google.protobuf.Method}
   */
  addMethods(opt_value, opt_index) {
    return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, Method, opt_index);
  };


  /**
   * Clears the list making it empty but non-null.
   * @return {!proto.google.protobuf.Api} returns this
   */
  clearMethodsList() {
    return this.setMethodsList([]);
  };


  /**
   * repeated Option options = 3;
   * @return {!Array<!proto.google.protobuf.Option>}
   */
  getOptionsList() {
    return /** @type{!Array<!proto.google.protobuf.Option>} */ (
      jspb.Message.getRepeatedWrapperField(this, Option, 3));
  }


  /**
   * @param {!Array<!proto.google.protobuf.Option>} value
   * @return {!proto.google.protobuf.Api} returns this
  */
  setOptionsList(value) {
    return jspb.Message.setRepeatedWrapperField(this, 3, value);
  }


  /**
   * Adds a value to the repeated field fieldName 
   *
   * @param {!proto.google.protobuf.Option=} opt_value
   * @param {number=} opt_index
   * @return {!proto.google.protobuf.Option}
   */
  addOptions(opt_value, opt_index) {
    return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, Option, opt_index);
  };


  /**
   * Clears the list making it empty but non-null.
   * @return {!proto.google.protobuf.Api} returns this
   */
  clearOptionsList() {
    return this.setOptionsList([]);
  };


  /**
   * optional string version = 4;
   * @return {string}
   */
  getVersion() {
    return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
  }

  /**
   * @param {string} value
   * @return {!proto.google.protobuf.Api} returns this
   */
  setVersion(value) {
    return jspb.Message.setProto3StringField(this, 4, value);
  }

  /**
   * optional SourceContext source_context = 5;
   * @return {?proto.google.protobuf.SourceContext}
   */
  getSourceContext() {
    return /** @type{?proto.google.protobuf.SourceContext} */ (
      jspb.Message.getWrapperField(this, SourceContext, 5));
  }


  /**
   * @param {?proto.google.protobuf.SourceContext|undefined} value
   * @return {!proto.google.protobuf.Api} returns this
  */
  setSourceContext(value) {
    return jspb.Message.setWrapperField(this, 5, value);
  }


  /**
   * Clears the message field making it undefined.
   * @return {!proto.google.protobuf.Api} returns this
   */
  clearSourceContext() {
    return this.setSourceContext(undefined);
  };


  /**
   * Returns whether this field is set.
   * @return {boolean}
   */
  hasSourceContext() {
    return jspb.Message.getField(this, 5) != null;
  }


  /**
   * repeated Mixin mixins = 6;
   * @return {!Array<!proto.google.protobuf.Mixin>}
   */
  getMixinsList() {
    return /** @type{!Array<!proto.google.protobuf.Mixin>} */ (
      jspb.Message.getRepeatedWrapperField(this, Mixin, 6));
  }


  /**
   * @param {!Array<!proto.google.protobuf.Mixin>} value
   * @return {!proto.google.protobuf.Api} returns this
  */
  setMixinsList(value) {
    return jspb.Message.setRepeatedWrapperField(this, 6, value);
  }


  /**
   * Adds a value to the repeated field fieldName 
   *
   * @param {!proto.google.protobuf.Mixin=} opt_value
   * @param {number=} opt_index
   * @return {!proto.google.protobuf.Mixin}
   */
  addMixins(opt_value, opt_index) {
    return jspb.Message.addToRepeatedWrapperField(this, 6, opt_value, Mixin, opt_index);
  };


  /**
   * Clears the list making it empty but non-null.
   * @return {!proto.google.protobuf.Api} returns this
   */
  clearMixinsList() {
    return this.setMixinsList([]);
  };


  /**
   * optional Syntax syntax = 7;
   * @return {!proto.google.protobuf.Syntax}
   */
  getSyntax() {
    return /** @type {!proto.google.protobuf.Syntax} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
  }

  /**
   * @param {!proto.google.protobuf.Syntax} value
   * @return {!proto.google.protobuf.Api} returns this
   */
  setSyntax(value) {
    return jspb.Message.setProto3EnumField(this, 7, value);
  }

  /**
   * optional string edition = 8;
   * @return {string}
   */
  getEdition() {
    return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
  }

  /**
   * @param {string} value
   * @return {!proto.google.protobuf.Api} returns this
   */
  setEdition(value) {
    return jspb.Message.setProto3StringField(this, 8, value);
  }

} // end class Api

/**
 * ES6 class generated by js_generator.cc.
 *
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
export class Method extends jspb.Message {
  /**
   * Generated by JsPbCodeGenerator.
   * @param {Array=} opt_data Optional initial data array, typically from a
   * server response, or constructed directly in Javascript. The array is used
   * in place and becomes part of the constructed object. It is not cloned.
   * If no data is provided, the constructed object will be empty, but still
   * valid.
   * @extends {jspb.Message}
   * @constructor
   */
  constructor(opt_data) {
    super(...arguments);
    jspb.Message.initialize(this, opt_data, 0, -1, Method.repeatedFields_, null);
  }

  /**
   * List of repeated fields within this message type.
   * @private {!Array<number>}
   * @const
   */
  static repeatedFields_ = [6];



  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  toObject(opt_includeInstance) {
    return Method.toObject(opt_includeInstance, this);
  }


  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!Method} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  static toObject(includeInstance, msg) {
    var f, obj = {
  name: jspb.Message.getFieldWithDefault(msg, 1, ""),
  requestTypeUrl: jspb.Message.getFieldWithDefault(msg, 2, ""),
  requestStreaming: jspb.Message.getBooleanFieldWithDefault(msg, 3, false),
  responseTypeUrl: jspb.Message.getFieldWithDefault(msg, 4, ""),
  responseStreaming: jspb.Message.getBooleanFieldWithDefault(msg, 5, false),
  optionsList: jspb.Message.toObjectList(msg.getOptionsList(),
      Option.toObject, includeInstance),
  syntax: jspb.Message.getFieldWithDefault(msg, 7, 0),
  edition: jspb.Message.getFieldWithDefault(msg, 8, "")
    };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  }


  /**
   * Deserializes binary data (in protobuf wire format).
   * @param {jspb.binary.bytesource.ByteSource} bytes The bytes to deserialize.
   * @return {!Method}
   */
  static deserializeBinary(bytes) {
    var reader = new jspb.BinaryReader(bytes);
    var msg = new Method;
    return Method.deserializeBinaryFromReader(msg, reader);
  }


  /**
   * Deserializes binary data (in protobuf wire format) from the
   * given reader into the given message object.
   * @param {!Method} msg The message object to deserialize into.
   * @param {!jspb.BinaryReader} reader The BinaryReader to use.
   * @return {!Method}
   */
  static deserializeBinaryFromReader(msg, reader) {
    while (reader.nextField()) {
      if (reader.isEndGroup()) {
        break;
      }
      var field = reader.getFieldNumber();
      switch (field) {
      case 1:
        var value = /** @type {string} */ (reader.readStringRequireUtf8());
        msg.setName(value);
        break;
      case 2:
        var value = /** @type {string} */ (reader.readStringRequireUtf8());
        msg.setRequestTypeUrl(value);
        break;
      case 3:
        var value = /** @type {boolean} */ (reader.readBool());
        msg.setRequestStreaming(value);
        break;
      case 4:
        var value = /** @type {string} */ (reader.readStringRequireUtf8());
        msg.setResponseTypeUrl(value);
        break;
      case 5:
        var value = /** @type {boolean} */ (reader.readBool());
        msg.setResponseStreaming(value);
        break;
      case 6:
        var value = new Option;
        reader.readMessage(value,Option.deserializeBinaryFromReader);
        msg.addOptions(value);
        break;
      case 7:
        var value = /** @type {!proto.google.protobuf.Syntax} */ (reader.readEnum());
        msg.setSyntax(value);
        break;
      case 8:
        var value = /** @type {string} */ (reader.readStringRequireUtf8());
        msg.setEdition(value);
        break;
      default:
        reader.skipField();
        break;
      }
    }
    return msg;
  }


  /**
   * Serializes the message to binary data (in protobuf wire format).
   * @return {!Uint8Array}
   */
  serializeBinary() {
    var writer = new jspb.BinaryWriter();
    this.constructor.serializeBinaryToWriter(this, writer);
    return writer.getResultBuffer();
  }


  /**
   * Serializes the given message to binary data (in protobuf wire
   * format), writing to the given BinaryWriter.
   * @param {!Method} message
   * @param {!jspb.BinaryWriter} writer
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  static serializeBinaryToWriter(message, writer) {
    var f = undefined;
    f = message.getName();
    if (f.length > 0) {
      writer.writeString(
        1,
        f
      );
    }
    f = message.getRequestTypeUrl();
    if (f.length > 0) {
      writer.writeString(
        2,
        f
      );
    }
    f = message.getRequestStreaming();
    if (f) {
      writer.writeBool(
        3,
        f
      );
    }
    f = message.getResponseTypeUrl();
    if (f.length > 0) {
      writer.writeString(
        4,
        f
      );
    }
    f = message.getResponseStreaming();
    if (f) {
      writer.writeBool(
        5,
        f
      );
    }
    f = message.getOptionsList();
    if (f.length > 0) {
      writer.writeRepeatedMessage(
        6,
        f,
        Option.serializeBinaryToWriter
      );
    }
    f = message.getSyntax();
    if (f !== 0.0) {
      writer.writeEnum(
        7,
        f
      );
    }
    f = message.getEdition();
    if (f.length > 0) {
      writer.writeString(
        8,
        f
      );
    }
  }


  /**
   * optional string name = 1;
   * @return {string}
   */
  getName() {
    return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
  }

  /**
   * @param {string} value
   * @return {!proto.google.protobuf.Method} returns this
   */
  setName(value) {
    return jspb.Message.setProto3StringField(this, 1, value);
  }

  /**
   * optional string request_type_url = 2;
   * @return {string}
   */
  getRequestTypeUrl() {
    return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
  }

  /**
   * @param {string} value
   * @return {!proto.google.protobuf.Method} returns this
   */
  setRequestTypeUrl(value) {
    return jspb.Message.setProto3StringField(this, 2, value);
  }

  /**
   * optional bool request_streaming = 3;
   * @return {boolean}
   */
  getRequestStreaming() {
    return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
  }

  /**
   * @param {boolean} value
   * @return {!proto.google.protobuf.Method} returns this
   */
  setRequestStreaming(value) {
    return jspb.Message.setProto3BooleanField(this, 3, value);
  }

  /**
   * optional string response_type_url = 4;
   * @return {string}
   */
  getResponseTypeUrl() {
    return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
  }

  /**
   * @param {string} value
   * @return {!proto.google.protobuf.Method} returns this
   */
  setResponseTypeUrl(value) {
    return jspb.Message.setProto3StringField(this, 4, value);
  }

  /**
   * optional bool response_streaming = 5;
   * @return {boolean}
   */
  getResponseStreaming() {
    return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 5, false));
  }

  /**
   * @param {boolean} value
   * @return {!proto.google.protobuf.Method} returns this
   */
  setResponseStreaming(value) {
    return jspb.Message.setProto3BooleanField(this, 5, value);
  }

  /**
   * repeated Option options = 6;
   * @return {!Array<!proto.google.protobuf.Option>}
   */
  getOptionsList() {
    return /** @type{!Array<!proto.google.protobuf.Option>} */ (
      jspb.Message.getRepeatedWrapperField(this, Option, 6));
  }


  /**
   * @param {!Array<!proto.google.protobuf.Option>} value
   * @return {!proto.google.protobuf.Method} returns this
  */
  setOptionsList(value) {
    return jspb.Message.setRepeatedWrapperField(this, 6, value);
  }


  /**
   * Adds a value to the repeated field fieldName 
   *
   * @param {!proto.google.protobuf.Option=} opt_value
   * @param {number=} opt_index
   * @return {!proto.google.protobuf.Option}
   */
  addOptions(opt_value, opt_index) {
    return jspb.Message.addToRepeatedWrapperField(this, 6, opt_value, Option, opt_index);
  };


  /**
   * Clears the list making it empty but non-null.
   * @return {!proto.google.protobuf.Method} returns this
   */
  clearOptionsList() {
    return this.setOptionsList([]);
  };


  /**
   * optional Syntax syntax = 7;
   * @return {!proto.google.protobuf.Syntax}
   */
  getSyntax() {
    return /** @type {!proto.google.protobuf.Syntax} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
  }

  /**
   * @param {!proto.google.protobuf.Syntax} value
   * @return {!proto.google.protobuf.Method} returns this
   */
  setSyntax(value) {
    return jspb.Message.setProto3EnumField(this, 7, value);
  }

  /**
   * optional string edition = 8;
   * @return {string}
   */
  getEdition() {
    return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
  }

  /**
   * @param {string} value
   * @return {!proto.google.protobuf.Method} returns this
   */
  setEdition(value) {
    return jspb.Message.setProto3StringField(this, 8, value);
  }

} // end class Method

/**
 * ES6 class generated by js_generator.cc.
 *
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
export class Mixin extends jspb.Message {
  /**
   * Generated by JsPbCodeGenerator.
   * @param {Array=} opt_data Optional initial data array, typically from a
   * server response, or constructed directly in Javascript. The array is used
   * in place and becomes part of the constructed object. It is not cloned.
   * If no data is provided, the constructed object will be empty, but still
   * valid.
   * @extends {jspb.Message}
   * @constructor
   */
  constructor(opt_data) {
    super(...arguments);
    jspb.Message.initialize(this, opt_data, 0, -1, null, null);
  }



  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  toObject(opt_includeInstance) {
    return Mixin.toObject(opt_includeInstance, this);
  }


  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!Mixin} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  static toObject(includeInstance, msg) {
    var f, obj = {
  name: jspb.Message.getFieldWithDefault(msg, 1, ""),
  root: jspb.Message.getFieldWithDefault(msg, 2, "")
    };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  }


  /**
   * Deserializes binary data (in protobuf wire format).
   * @param {jspb.binary.bytesource.ByteSource} bytes The bytes to deserialize.
   * @return {!Mixin}
   */
  static deserializeBinary(bytes) {
    var reader = new jspb.BinaryReader(bytes);
    var msg = new Mixin;
    return Mixin.deserializeBinaryFromReader(msg, reader);
  }


  /**
   * Deserializes binary data (in protobuf wire format) from the
   * given reader into the given message object.
   * @param {!Mixin} msg The message object to deserialize into.
   * @param {!jspb.BinaryReader} reader The BinaryReader to use.
   * @return {!Mixin}
   */
  static deserializeBinaryFromReader(msg, reader) {
    while (reader.nextField()) {
      if (reader.isEndGroup()) {
        break;
      }
      var field = reader.getFieldNumber();
      switch (field) {
      case 1:
        var value = /** @type {string} */ (reader.readStringRequireUtf8());
        msg.setName(value);
        break;
      case 2:
        var value = /** @type {string} */ (reader.readStringRequireUtf8());
        msg.setRoot(value);
        break;
      default:
        reader.skipField();
        break;
      }
    }
    return msg;
  }


  /**
   * Serializes the message to binary data (in protobuf wire format).
   * @return {!Uint8Array}
   */
  serializeBinary() {
    var writer = new jspb.BinaryWriter();
    this.constructor.serializeBinaryToWriter(this, writer);
    return writer.getResultBuffer();
  }


  /**
   * Serializes the given message to binary data (in protobuf wire
   * format), writing to the given BinaryWriter.
   * @param {!Mixin} message
   * @param {!jspb.BinaryWriter} writer
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  static serializeBinaryToWriter(message, writer) {
    var f = undefined;
    f = message.getName();
    if (f.length > 0) {
      writer.writeString(
        1,
        f
      );
    }
    f = message.getRoot();
    if (f.length > 0) {
      writer.writeString(
        2,
        f
      );
    }
  }


  /**
   * optional string name = 1;
   * @return {string}
   */
  getName() {
    return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
  }

  /**
   * @param {string} value
   * @return {!proto.google.protobuf.Mixin} returns this
   */
  setName(value) {
    return jspb.Message.setProto3StringField(this, 1, value);
  }

  /**
   * optional string root = 2;
   * @return {string}
   */
  getRoot() {
    return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
  }

  /**
   * @param {string} value
   * @return {!proto.google.protobuf.Mixin} returns this
   */
  setRoot(value) {
    return jspb.Message.setProto3StringField(this, 2, value);
  }

} // end class Mixin
