// source: google/protobuf/field_mask.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

import jspb from "google-protobuf";

/**
 * ES6 class generated by js_generator.cc.
 *
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
export class FieldMask extends jspb.Message {
  /**
   * Generated by JsPbCodeGenerator.
   * @param {Array=} opt_data Optional initial data array, typically from a
   * server response, or constructed directly in Javascript. The array is used
   * in place and becomes part of the constructed object. It is not cloned.
   * If no data is provided, the constructed object will be empty, but still
   * valid.
   * @extends {jspb.Message}
   * @constructor
   */
  constructor(opt_data) {
    super(...arguments);
    jspb.Message.initialize(this, opt_data, 0, -1, FieldMask.repeatedFields_, null);
  }

  /**
   * List of repeated fields within this message type.
   * @private {!Array<number>}
   * @const
   */
  static repeatedFields_ = [1];



  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  toObject(opt_includeInstance) {
    return FieldMask.toObject(opt_includeInstance, this);
  }


  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!FieldMask} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  static toObject(includeInstance, msg) {
    var f, obj = {
  pathsList: (f = jspb.Message.getRepeatedField(msg, 1)) == null ? undefined : f
    };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  }


  /**
   * Deserializes binary data (in protobuf wire format).
   * @param {jspb.binary.bytesource.ByteSource} bytes The bytes to deserialize.
   * @return {!FieldMask}
   */
  static deserializeBinary(bytes) {
    var reader = new jspb.BinaryReader(bytes);
    var msg = new FieldMask;
    return FieldMask.deserializeBinaryFromReader(msg, reader);
  }


  /**
   * Deserializes binary data (in protobuf wire format) from the
   * given reader into the given message object.
   * @param {!FieldMask} msg The message object to deserialize into.
   * @param {!jspb.BinaryReader} reader The BinaryReader to use.
   * @return {!FieldMask}
   */
  static deserializeBinaryFromReader(msg, reader) {
    while (reader.nextField()) {
      if (reader.isEndGroup()) {
        break;
      }
      var field = reader.getFieldNumber();
      switch (field) {
      case 1:
        var value = /** @type {string} */ (reader.readStringRequireUtf8());
        msg.addPaths(value);
        break;
      default:
        reader.skipField();
        break;
      }
    }
    return msg;
  }


  /**
   * Serializes the message to binary data (in protobuf wire format).
   * @return {!Uint8Array}
   */
  serializeBinary() {
    var writer = new jspb.BinaryWriter();
    this.constructor.serializeBinaryToWriter(this, writer);
    return writer.getResultBuffer();
  }


  /**
   * Serializes the given message to binary data (in protobuf wire
   * format), writing to the given BinaryWriter.
   * @param {!FieldMask} message
   * @param {!jspb.BinaryWriter} writer
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  static serializeBinaryToWriter(message, writer) {
    var f = undefined;
    f = message.getPathsList();
    if (f.length > 0) {
      writer.writeRepeatedString(
        1,
        f
      );
    }
  }


  /**
   * repeated string paths = 1;
   * @return {!Array<string>}
   */
  getPathsList() {
    return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 1));
  }

  /**
   * @param {!Array<string>} value
   * @return {!proto.google.protobuf.FieldMask} returns this
   */
  setPathsList(value) {
    return jspb.Message.setField(this, 1, value || []);
  };


  /**
   * Adds a value to the repeated field addPaths 
   *
   * @param {string} value
   * @param {number=} opt_index
   * @return {!proto.google.protobuf.FieldMask} returns this
   */
  addPaths(value, opt_index) {
    return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
  };


  /**
   * Clears the list making it empty but non-null.
   * @return {!proto.google.protobuf.FieldMask} returns this
   */
  clearPathsList() {
    return this.setPathsList([]);
  };


} // end class FieldMask
