// source: google/protobuf/struct.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

import jspb from "google-protobuf";

/**
 * ES6 class generated by js_generator.cc.
 *
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
export class Struct extends jspb.Message {
  /**
   * Generated by JsPbCodeGenerator.
   * @param {Array=} opt_data Optional initial data array, typically from a
   * server response, or constructed directly in Javascript. The array is used
   * in place and becomes part of the constructed object. It is not cloned.
   * If no data is provided, the constructed object will be empty, but still
   * valid.
   * @extends {jspb.Message}
   * @constructor
   */
  constructor(opt_data) {
    super(...arguments);
    jspb.Message.initialize(this, opt_data, 0, -1, null, null);
  }



  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  toObject(opt_includeInstance) {
    return Struct.toObject(opt_includeInstance, this);
  }


  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!Struct} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  static toObject(includeInstance, msg) {
    var f, obj = {
  fieldsMap: (f = msg.getFieldsMap()) ? f.toObject(includeInstance, proto.google.protobuf.Value.toObject) : []
    };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  }


  /**
   * Deserializes binary data (in protobuf wire format).
   * @param {jspb.binary.bytesource.ByteSource} bytes The bytes to deserialize.
   * @return {!Struct}
   */
  static deserializeBinary(bytes) {
    var reader = new jspb.BinaryReader(bytes);
    var msg = new Struct;
    return Struct.deserializeBinaryFromReader(msg, reader);
  }


  /**
   * Deserializes binary data (in protobuf wire format) from the
   * given reader into the given message object.
   * @param {!Struct} msg The message object to deserialize into.
   * @param {!jspb.BinaryReader} reader The BinaryReader to use.
   * @return {!Struct}
   */
  static deserializeBinaryFromReader(msg, reader) {
    while (reader.nextField()) {
      if (reader.isEndGroup()) {
        break;
      }
      var field = reader.getFieldNumber();
      switch (field) {
      case 1:
        var value = msg.getFieldsMap();
        reader.readMessage(value, function(message, reader) {
          jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readStringRequireUtf8, jspb.BinaryReader.prototype.readMessage, proto.google.protobuf.Value.deserializeBinaryFromReader, "", new proto.google.protobuf.Value());
           });
        break;
      default:
        reader.skipField();
        break;
      }
    }
    return msg;
  }


  /**
   * Serializes the message to binary data (in protobuf wire format).
   * @return {!Uint8Array}
   */
  serializeBinary() {
    var writer = new jspb.BinaryWriter();
    this.constructor.serializeBinaryToWriter(this, writer);
    return writer.getResultBuffer();
  }


  /**
   * Serializes the given message to binary data (in protobuf wire
   * format), writing to the given BinaryWriter.
   * @param {!Struct} message
   * @param {!jspb.BinaryWriter} writer
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  static serializeBinaryToWriter(message, writer) {
    var f = undefined;
    f = message.getFieldsMap(true);
    if (f && f.getLength() > 0) {
  jspb.internal.public_for_gencode.serializeMapToBinary(
      message.getFieldsMap(true),
      1,
      writer,
      jspb.BinaryWriter.prototype.writeString,
      jspb.BinaryWriter.prototype.writeMessage,
      proto.google.protobuf.Value.serializeBinaryToWriter);
    }
  }


  /**
   * map<string, Value> fields = 1;
   * @param {boolean=} opt_noLazyCreate Do not create the map if
   * empty, instead returning `undefined`
   * @return {!jspb.Map<string,!proto.google.protobuf.Value>}
   */
  getFieldsMap(opt_noLazyCreate) {
    return /** @type {!jspb.Map<string,!proto.google.protobuf.Value>} */ (
        jspb.Message.getMapField(this, 1, opt_noLazyCreate,
        proto.google.protobuf.Value));
  }


  /**
   * Clears values from the map. The map will be non-null.
   * @return {!proto.google.protobuf.Struct} returns this
   */
  clearFieldsMap() {
    this.getFieldsMap().clear();
    return this;
  }


} // end class Struct

/**
 * ES6 class generated by js_generator.cc.
 *
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
export class Value extends jspb.Message {
  /**
   * Generated by JsPbCodeGenerator.
   * @param {Array=} opt_data Optional initial data array, typically from a
   * server response, or constructed directly in Javascript. The array is used
   * in place and becomes part of the constructed object. It is not cloned.
   * If no data is provided, the constructed object will be empty, but still
   * valid.
   * @extends {jspb.Message}
   * @constructor
   */
  constructor(opt_data) {
    super(...arguments);
    jspb.Message.initialize(this, opt_data, 0, -1, null, Value.oneofGroups_);
  }

  /**
   * Oneof group definitions for this message. Each group defines the field
   * numbers belonging to that group. When of these fields' value is set, all
   * other fields in the group are cleared. During deserialization, if multiple
   * fields are encountered for a group, only the last value seen will be kept.
   * @private {!Array<!Array<number>>}
   * @const
   */
  static oneofGroups_ = [[1,2,3,4,5,6]];

  /**
   * @enum {number}
   */
  static KindCase = {
    KIND_NOT_SET: 0,
    NULL_VALUE: 1,
    NUMBER_VALUE: 2,
    STRING_VALUE: 3,
    BOOL_VALUE: 4,
    STRUCT_VALUE: 5,
    LIST_VALUE: 6
  };

  /**
   * @return {Value.KindCase}
   */
  getKindCase() {
    return /** @type {Value.KindCase} */(jspb.Message.computeOneofCase(this, Value.oneofGroups_[0]));
  }



  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  toObject(opt_includeInstance) {
    return Value.toObject(opt_includeInstance, this);
  }


  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!Value} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  static toObject(includeInstance, msg) {
    var f, obj = {
  nullValue: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
  numberValue: (f = jspb.Message.getOptionalFloatingPointField(msg, 2)) == null ? undefined : f,
  stringValue: (f = jspb.Message.getField(msg, 3)) == null ? undefined : f,
  boolValue: (f = jspb.Message.getBooleanField(msg, 4)) == null ? undefined : f,
  structValue: (f = msg.getStructValue()) && Struct.toObject(includeInstance, f),
  listValue: (f = msg.getListValue()) && ListValue.toObject(includeInstance, f)
    };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  }


  /**
   * Deserializes binary data (in protobuf wire format).
   * @param {jspb.binary.bytesource.ByteSource} bytes The bytes to deserialize.
   * @return {!Value}
   */
  static deserializeBinary(bytes) {
    var reader = new jspb.BinaryReader(bytes);
    var msg = new Value;
    return Value.deserializeBinaryFromReader(msg, reader);
  }


  /**
   * Deserializes binary data (in protobuf wire format) from the
   * given reader into the given message object.
   * @param {!Value} msg The message object to deserialize into.
   * @param {!jspb.BinaryReader} reader The BinaryReader to use.
   * @return {!Value}
   */
  static deserializeBinaryFromReader(msg, reader) {
    while (reader.nextField()) {
      if (reader.isEndGroup()) {
        break;
      }
      var field = reader.getFieldNumber();
      switch (field) {
      case 1:
        var value = /** @type {!proto.google.protobuf.NullValue} */ (reader.readEnum());
        msg.setNullValue(value);
        break;
      case 2:
        var value = /** @type {number} */ (reader.readDouble());
        msg.setNumberValue(value);
        break;
      case 3:
        var value = /** @type {string} */ (reader.readStringRequireUtf8());
        msg.setStringValue(value);
        break;
      case 4:
        var value = /** @type {boolean} */ (reader.readBool());
        msg.setBoolValue(value);
        break;
      case 5:
        var value = new Struct;
        reader.readMessage(value,Struct.deserializeBinaryFromReader);
        msg.setStructValue(value);
        break;
      case 6:
        var value = new ListValue;
        reader.readMessage(value,ListValue.deserializeBinaryFromReader);
        msg.setListValue(value);
        break;
      default:
        reader.skipField();
        break;
      }
    }
    return msg;
  }


  /**
   * Serializes the message to binary data (in protobuf wire format).
   * @return {!Uint8Array}
   */
  serializeBinary() {
    var writer = new jspb.BinaryWriter();
    this.constructor.serializeBinaryToWriter(this, writer);
    return writer.getResultBuffer();
  }


  /**
   * Serializes the given message to binary data (in protobuf wire
   * format), writing to the given BinaryWriter.
   * @param {!Value} message
   * @param {!jspb.BinaryWriter} writer
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  static serializeBinaryToWriter(message, writer) {
    var f = undefined;
    f = /** @type {!proto.google.protobuf.NullValue} */ (jspb.Message.getField(message, 1));
    if (f != null) {
      writer.writeEnum(
        1,
        f
      );
    }
    f = /** @type {number} */ (jspb.Message.getField(message, 2));
    if (f != null) {
      writer.writeDouble(
        2,
        f
      );
    }
    f = /** @type {string} */ (jspb.Message.getField(message, 3));
    if (f != null) {
      writer.writeString(
        3,
        f
      );
    }
    f = /** @type {boolean} */ (jspb.Message.getField(message, 4));
    if (f != null) {
      writer.writeBool(
        4,
        f
      );
    }
    f = message.getStructValue();
    if (f != null) {
      writer.writeMessage(
        5,
        f,
        Struct.serializeBinaryToWriter
      );
    }
    f = message.getListValue();
    if (f != null) {
      writer.writeMessage(
        6,
        f,
        ListValue.serializeBinaryToWriter
      );
    }
  }


  /**
   * optional NullValue null_value = 1;
   * @return {!proto.google.protobuf.NullValue}
   */
  getNullValue() {
    return /** @type {!proto.google.protobuf.NullValue} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
  }

  /**
   * @param {!proto.google.protobuf.NullValue} value
   * @return {!proto.google.protobuf.Value} returns this
   */
  setNullValue(value) {
    return jspb.Message.setOneofField(this, 1, Value.oneofGroups_[0], value);
  };


  /**
   * Clears the field making it undefined.
   * @return {!proto.google.protobuf.Value} returns this
   */
  clearNullValue() {
    return jspb.Message.setOneofField(this, 1, Value.oneofGroups_[0], undefined);
  };


  /**
   * Returns whether this field is set.
   * @return {boolean}
   */
  hasNullValue() {
    return jspb.Message.getField(this, 1) != null;
  }


  /**
   * optional double number_value = 2;
   * @return {number}
   */
  getNumberValue() {
    return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
  }

  /**
   * @param {number} value
   * @return {!proto.google.protobuf.Value} returns this
   */
  setNumberValue(value) {
    return jspb.Message.setOneofField(this, 2, Value.oneofGroups_[0], value);
  };


  /**
   * Clears the field making it undefined.
   * @return {!proto.google.protobuf.Value} returns this
   */
  clearNumberValue() {
    return jspb.Message.setOneofField(this, 2, Value.oneofGroups_[0], undefined);
  };


  /**
   * Returns whether this field is set.
   * @return {boolean}
   */
  hasNumberValue() {
    return jspb.Message.getField(this, 2) != null;
  }


  /**
   * optional string string_value = 3;
   * @return {string}
   */
  getStringValue() {
    return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
  }

  /**
   * @param {string} value
   * @return {!proto.google.protobuf.Value} returns this
   */
  setStringValue(value) {
    return jspb.Message.setOneofField(this, 3, Value.oneofGroups_[0], value);
  };


  /**
   * Clears the field making it undefined.
   * @return {!proto.google.protobuf.Value} returns this
   */
  clearStringValue() {
    return jspb.Message.setOneofField(this, 3, Value.oneofGroups_[0], undefined);
  };


  /**
   * Returns whether this field is set.
   * @return {boolean}
   */
  hasStringValue() {
    return jspb.Message.getField(this, 3) != null;
  }


  /**
   * optional bool bool_value = 4;
   * @return {boolean}
   */
  getBoolValue() {
    return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 4, false));
  }

  /**
   * @param {boolean} value
   * @return {!proto.google.protobuf.Value} returns this
   */
  setBoolValue(value) {
    return jspb.Message.setOneofField(this, 4, Value.oneofGroups_[0], value);
  };


  /**
   * Clears the field making it undefined.
   * @return {!proto.google.protobuf.Value} returns this
   */
  clearBoolValue() {
    return jspb.Message.setOneofField(this, 4, Value.oneofGroups_[0], undefined);
  };


  /**
   * Returns whether this field is set.
   * @return {boolean}
   */
  hasBoolValue() {
    return jspb.Message.getField(this, 4) != null;
  }


  /**
   * optional Struct struct_value = 5;
   * @return {?proto.google.protobuf.Struct}
   */
  getStructValue() {
    return /** @type{?proto.google.protobuf.Struct} */ (
      jspb.Message.getWrapperField(this, Struct, 5));
  }


  /**
   * @param {?proto.google.protobuf.Struct|undefined} value
   * @return {!proto.google.protobuf.Value} returns this
  */
  setStructValue(value) {
    return jspb.Message.setOneofWrapperField(this, 5, Value.oneofGroups_[0], value);
  }


  /**
   * Clears the message field making it undefined.
   * @return {!proto.google.protobuf.Value} returns this
   */
  clearStructValue() {
    return this.setStructValue(undefined);
  };


  /**
   * Returns whether this field is set.
   * @return {boolean}
   */
  hasStructValue() {
    return jspb.Message.getField(this, 5) != null;
  }


  /**
   * optional ListValue list_value = 6;
   * @return {?proto.google.protobuf.ListValue}
   */
  getListValue() {
    return /** @type{?proto.google.protobuf.ListValue} */ (
      jspb.Message.getWrapperField(this, ListValue, 6));
  }


  /**
   * @param {?proto.google.protobuf.ListValue|undefined} value
   * @return {!proto.google.protobuf.Value} returns this
  */
  setListValue(value) {
    return jspb.Message.setOneofWrapperField(this, 6, Value.oneofGroups_[0], value);
  }


  /**
   * Clears the message field making it undefined.
   * @return {!proto.google.protobuf.Value} returns this
   */
  clearListValue() {
    return this.setListValue(undefined);
  };


  /**
   * Returns whether this field is set.
   * @return {boolean}
   */
  hasListValue() {
    return jspb.Message.getField(this, 6) != null;
  }


} // end class Value

/**
 * ES6 class generated by js_generator.cc.
 *
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
export class ListValue extends jspb.Message {
  /**
   * Generated by JsPbCodeGenerator.
   * @param {Array=} opt_data Optional initial data array, typically from a
   * server response, or constructed directly in Javascript. The array is used
   * in place and becomes part of the constructed object. It is not cloned.
   * If no data is provided, the constructed object will be empty, but still
   * valid.
   * @extends {jspb.Message}
   * @constructor
   */
  constructor(opt_data) {
    super(...arguments);
    jspb.Message.initialize(this, opt_data, 0, -1, ListValue.repeatedFields_, null);
  }

  /**
   * List of repeated fields within this message type.
   * @private {!Array<number>}
   * @const
   */
  static repeatedFields_ = [1];



  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  toObject(opt_includeInstance) {
    return ListValue.toObject(opt_includeInstance, this);
  }


  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!ListValue} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  static toObject(includeInstance, msg) {
    var f, obj = {
  valuesList: jspb.Message.toObjectList(msg.getValuesList(),
      Value.toObject, includeInstance)
    };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  }


  /**
   * Deserializes binary data (in protobuf wire format).
   * @param {jspb.binary.bytesource.ByteSource} bytes The bytes to deserialize.
   * @return {!ListValue}
   */
  static deserializeBinary(bytes) {
    var reader = new jspb.BinaryReader(bytes);
    var msg = new ListValue;
    return ListValue.deserializeBinaryFromReader(msg, reader);
  }


  /**
   * Deserializes binary data (in protobuf wire format) from the
   * given reader into the given message object.
   * @param {!ListValue} msg The message object to deserialize into.
   * @param {!jspb.BinaryReader} reader The BinaryReader to use.
   * @return {!ListValue}
   */
  static deserializeBinaryFromReader(msg, reader) {
    while (reader.nextField()) {
      if (reader.isEndGroup()) {
        break;
      }
      var field = reader.getFieldNumber();
      switch (field) {
      case 1:
        var value = new Value;
        reader.readMessage(value,Value.deserializeBinaryFromReader);
        msg.addValues(value);
        break;
      default:
        reader.skipField();
        break;
      }
    }
    return msg;
  }


  /**
   * Serializes the message to binary data (in protobuf wire format).
   * @return {!Uint8Array}
   */
  serializeBinary() {
    var writer = new jspb.BinaryWriter();
    this.constructor.serializeBinaryToWriter(this, writer);
    return writer.getResultBuffer();
  }


  /**
   * Serializes the given message to binary data (in protobuf wire
   * format), writing to the given BinaryWriter.
   * @param {!ListValue} message
   * @param {!jspb.BinaryWriter} writer
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  static serializeBinaryToWriter(message, writer) {
    var f = undefined;
    f = message.getValuesList();
    if (f.length > 0) {
      writer.writeRepeatedMessage(
        1,
        f,
        Value.serializeBinaryToWriter
      );
    }
  }


  /**
   * repeated Value values = 1;
   * @return {!Array<!proto.google.protobuf.Value>}
   */
  getValuesList() {
    return /** @type{!Array<!proto.google.protobuf.Value>} */ (
      jspb.Message.getRepeatedWrapperField(this, Value, 1));
  }


  /**
   * @param {!Array<!proto.google.protobuf.Value>} value
   * @return {!proto.google.protobuf.ListValue} returns this
  */
  setValuesList(value) {
    return jspb.Message.setRepeatedWrapperField(this, 1, value);
  }


  /**
   * Adds a value to the repeated field fieldName 
   *
   * @param {!proto.google.protobuf.Value=} opt_value
   * @param {number=} opt_index
   * @return {!proto.google.protobuf.Value}
   */
  addValues(opt_value, opt_index) {
    return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, Value, opt_index);
  };


  /**
   * Clears the list making it empty but non-null.
   * @return {!proto.google.protobuf.ListValue} returns this
   */
  clearValuesList() {
    return this.setValuesList([]);
  };


} // end class ListValue
/**
 * @enum {number}
 */
export const NullValue = {
  NULL_VALUE: 0
};

/* This code will be inserted into generated code for
 * google/protobuf/struct.proto. */

/**
 * Typedef representing plain JavaScript values that can go into a
 *     Struct.
 * @typedef {null|number|string|boolean|Array|Object}
 */
// JavaScriptValue;


/**
 * Converts this Value object to a plain JavaScript value.
 * @return {?JavaScriptValue} a plain JavaScript
 *     value representing this Struct.
 */
Value.prototype.toJavaScript = function() {
  var kindCase = Value.KindCase;
  switch (this.getKindCase()) {
    case kindCase.NULL_VALUE:
      return null;
    case kindCase.NUMBER_VALUE:
      return this.getNumberValue();
    case kindCase.STRING_VALUE:
      return this.getStringValue();
    case kindCase.BOOL_VALUE:
      return this.getBoolValue();
    case kindCase.STRUCT_VALUE:
      return this.getStructValue().toJavaScript();
    case kindCase.LIST_VALUE:
      return this.getListValue().toJavaScript();
    default:
      throw new Error('Unexpected struct type');
  }
};


/**
 * Converts this JavaScript value to a new Value proto.
 * @param {!JavaScriptValue} value The value to
 *     convert.
 * @return {!Value} The newly constructed value.
 */
Value.fromJavaScript = function(value) {
  var ret = new Value();
  switch (goog.typeOf(value)) {
    case 'string':
      ret.setStringValue(/** @type {string} */ (value));
      break;
    case 'number':
      ret.setNumberValue(/** @type {number} */ (value));
      break;
    case 'boolean':
      ret.setBoolValue(/** @type {boolean} */ (value));
      break;
    case 'null':
      ret.setNullValue(NullValue.NULL_VALUE);
      break;
    case 'array':
      ret.setListValue(ListValue.fromJavaScript(
          /** @type{!Array} */ (value)));
      break;
    case 'object':
      ret.setStructValue(Struct.fromJavaScript(
          /** @type{!Object} */ (value)));
      break;
    default:
      throw new Error('Unexpected struct type.');
  }

  return ret;
};


/**
 * Converts this ListValue object to a plain JavaScript array.
 * @return {!Array} a plain JavaScript array representing this List.
 */
ListValue.prototype.toJavaScript = function() {
  var ret = [];
  var values = this.getValuesList();

  for (var i = 0; i < values.length; i++) {
    ret[i] = values[i].toJavaScript();
  }

  return ret;
};


/**
 * Constructs a ListValue protobuf from this plain JavaScript array.
 * @param {!Array} array a plain JavaScript array
 * @return {ListValue} a new ListValue object
 */
ListValue.fromJavaScript = function(array) {
  var ret = new ListValue();

  for (var i = 0; i < array.length; i++) {
    ret.addValues(Value.fromJavaScript(array[i]));
  }

  return ret;
};


/**
 * Converts this Struct object to a plain JavaScript object.
 * @return {!Object<string, !JavaScriptValue>} a plain
 *     JavaScript object representing this Struct.
 */
Struct.prototype.toJavaScript = function() {
  var ret = {};

  this.getFieldsMap().forEach(function(value, key) {
    ret[key] = value.toJavaScript();
  });

  return ret;
};


/**
 * Constructs a Struct protobuf from this plain JavaScript object.
 * @param {!Object} obj a plain JavaScript object
 * @return {Struct} a new Struct object
 */
Struct.fromJavaScript = function(obj) {
  var ret = new Struct();
  var map = ret.getFieldsMap();

  for (var property in obj) {
    var val = obj[property];
    map.set(property, Value.fromJavaScript(val));
  }

  return ret;
};
