// source: google/protobuf/type.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

import jspb from "google-protobuf";
import {Any} from "google-protobuf/google/protobuf/any_pb.mjs"; // proto import: "google/protobuf/any.proto"
import {SourceContext} from "google-protobuf/google/protobuf/source_context_pb.mjs"; // proto import: "google/protobuf/source_context.proto"

/**
 * ES6 class generated by js_generator.cc.
 *
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
export class Type extends jspb.Message {
  /**
   * Generated by JsPbCodeGenerator.
   * @param {Array=} opt_data Optional initial data array, typically from a
   * server response, or constructed directly in Javascript. The array is used
   * in place and becomes part of the constructed object. It is not cloned.
   * If no data is provided, the constructed object will be empty, but still
   * valid.
   * @extends {jspb.Message}
   * @constructor
   */
  constructor(opt_data) {
    super(...arguments);
    jspb.Message.initialize(this, opt_data, 0, -1, Type.repeatedFields_, null);
  }

  /**
   * List of repeated fields within this message type.
   * @private {!Array<number>}
   * @const
   */
  static repeatedFields_ = [2,3,4];



  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  toObject(opt_includeInstance) {
    return Type.toObject(opt_includeInstance, this);
  }


  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!Type} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  static toObject(includeInstance, msg) {
    var f, obj = {
  name: jspb.Message.getFieldWithDefault(msg, 1, ""),
  fieldsList: jspb.Message.toObjectList(msg.getFieldsList(),
      Field.toObject, includeInstance),
  oneofsList: (f = jspb.Message.getRepeatedField(msg, 3)) == null ? undefined : f,
  optionsList: jspb.Message.toObjectList(msg.getOptionsList(),
      Option.toObject, includeInstance),
  sourceContext: (f = msg.getSourceContext()) && SourceContext.toObject(includeInstance, f),
  syntax: jspb.Message.getFieldWithDefault(msg, 6, 0),
  edition: jspb.Message.getFieldWithDefault(msg, 7, "")
    };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  }


  /**
   * Deserializes binary data (in protobuf wire format).
   * @param {jspb.binary.bytesource.ByteSource} bytes The bytes to deserialize.
   * @return {!Type}
   */
  static deserializeBinary(bytes) {
    var reader = new jspb.BinaryReader(bytes);
    var msg = new Type;
    return Type.deserializeBinaryFromReader(msg, reader);
  }


  /**
   * Deserializes binary data (in protobuf wire format) from the
   * given reader into the given message object.
   * @param {!Type} msg The message object to deserialize into.
   * @param {!jspb.BinaryReader} reader The BinaryReader to use.
   * @return {!Type}
   */
  static deserializeBinaryFromReader(msg, reader) {
    while (reader.nextField()) {
      if (reader.isEndGroup()) {
        break;
      }
      var field = reader.getFieldNumber();
      switch (field) {
      case 1:
        var value = /** @type {string} */ (reader.readStringRequireUtf8());
        msg.setName(value);
        break;
      case 2:
        var value = new Field;
        reader.readMessage(value,Field.deserializeBinaryFromReader);
        msg.addFields(value);
        break;
      case 3:
        var value = /** @type {string} */ (reader.readStringRequireUtf8());
        msg.addOneofs(value);
        break;
      case 4:
        var value = new Option;
        reader.readMessage(value,Option.deserializeBinaryFromReader);
        msg.addOptions(value);
        break;
      case 5:
        var value = new SourceContext;
        reader.readMessage(value,SourceContext.deserializeBinaryFromReader);
        msg.setSourceContext(value);
        break;
      case 6:
        var value = /** @type {!proto.google.protobuf.Syntax} */ (reader.readEnum());
        msg.setSyntax(value);
        break;
      case 7:
        var value = /** @type {string} */ (reader.readStringRequireUtf8());
        msg.setEdition(value);
        break;
      default:
        reader.skipField();
        break;
      }
    }
    return msg;
  }


  /**
   * Serializes the message to binary data (in protobuf wire format).
   * @return {!Uint8Array}
   */
  serializeBinary() {
    var writer = new jspb.BinaryWriter();
    this.constructor.serializeBinaryToWriter(this, writer);
    return writer.getResultBuffer();
  }


  /**
   * Serializes the given message to binary data (in protobuf wire
   * format), writing to the given BinaryWriter.
   * @param {!Type} message
   * @param {!jspb.BinaryWriter} writer
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  static serializeBinaryToWriter(message, writer) {
    var f = undefined;
    f = message.getName();
    if (f.length > 0) {
      writer.writeString(
        1,
        f
      );
    }
    f = message.getFieldsList();
    if (f.length > 0) {
      writer.writeRepeatedMessage(
        2,
        f,
        Field.serializeBinaryToWriter
      );
    }
    f = message.getOneofsList();
    if (f.length > 0) {
      writer.writeRepeatedString(
        3,
        f
      );
    }
    f = message.getOptionsList();
    if (f.length > 0) {
      writer.writeRepeatedMessage(
        4,
        f,
        Option.serializeBinaryToWriter
      );
    }
    f = message.getSourceContext();
    if (f != null) {
      writer.writeMessage(
        5,
        f,
        SourceContext.serializeBinaryToWriter
      );
    }
    f = message.getSyntax();
    if (f !== 0.0) {
      writer.writeEnum(
        6,
        f
      );
    }
    f = message.getEdition();
    if (f.length > 0) {
      writer.writeString(
        7,
        f
      );
    }
  }


  /**
   * optional string name = 1;
   * @return {string}
   */
  getName() {
    return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
  }

  /**
   * @param {string} value
   * @return {!proto.google.protobuf.Type} returns this
   */
  setName(value) {
    return jspb.Message.setProto3StringField(this, 1, value);
  }

  /**
   * repeated Field fields = 2;
   * @return {!Array<!proto.google.protobuf.Field>}
   */
  getFieldsList() {
    return /** @type{!Array<!proto.google.protobuf.Field>} */ (
      jspb.Message.getRepeatedWrapperField(this, Field, 2));
  }


  /**
   * @param {!Array<!proto.google.protobuf.Field>} value
   * @return {!proto.google.protobuf.Type} returns this
  */
  setFieldsList(value) {
    return jspb.Message.setRepeatedWrapperField(this, 2, value);
  }


  /**
   * Adds a value to the repeated field fieldName 
   *
   * @param {!proto.google.protobuf.Field=} opt_value
   * @param {number=} opt_index
   * @return {!proto.google.protobuf.Field}
   */
  addFields(opt_value, opt_index) {
    return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, Field, opt_index);
  };


  /**
   * Clears the list making it empty but non-null.
   * @return {!proto.google.protobuf.Type} returns this
   */
  clearFieldsList() {
    return this.setFieldsList([]);
  };


  /**
   * repeated string oneofs = 3;
   * @return {!Array<string>}
   */
  getOneofsList() {
    return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 3));
  }

  /**
   * @param {!Array<string>} value
   * @return {!proto.google.protobuf.Type} returns this
   */
  setOneofsList(value) {
    return jspb.Message.setField(this, 3, value || []);
  };


  /**
   * Adds a value to the repeated field addOneofs 
   *
   * @param {string} value
   * @param {number=} opt_index
   * @return {!proto.google.protobuf.Type} returns this
   */
  addOneofs(value, opt_index) {
    return jspb.Message.addToRepeatedField(this, 3, value, opt_index);
  };


  /**
   * Clears the list making it empty but non-null.
   * @return {!proto.google.protobuf.Type} returns this
   */
  clearOneofsList() {
    return this.setOneofsList([]);
  };


  /**
   * repeated Option options = 4;
   * @return {!Array<!proto.google.protobuf.Option>}
   */
  getOptionsList() {
    return /** @type{!Array<!proto.google.protobuf.Option>} */ (
      jspb.Message.getRepeatedWrapperField(this, Option, 4));
  }


  /**
   * @param {!Array<!proto.google.protobuf.Option>} value
   * @return {!proto.google.protobuf.Type} returns this
  */
  setOptionsList(value) {
    return jspb.Message.setRepeatedWrapperField(this, 4, value);
  }


  /**
   * Adds a value to the repeated field fieldName 
   *
   * @param {!proto.google.protobuf.Option=} opt_value
   * @param {number=} opt_index
   * @return {!proto.google.protobuf.Option}
   */
  addOptions(opt_value, opt_index) {
    return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, Option, opt_index);
  };


  /**
   * Clears the list making it empty but non-null.
   * @return {!proto.google.protobuf.Type} returns this
   */
  clearOptionsList() {
    return this.setOptionsList([]);
  };


  /**
   * optional SourceContext source_context = 5;
   * @return {?proto.google.protobuf.SourceContext}
   */
  getSourceContext() {
    return /** @type{?proto.google.protobuf.SourceContext} */ (
      jspb.Message.getWrapperField(this, SourceContext, 5));
  }


  /**
   * @param {?proto.google.protobuf.SourceContext|undefined} value
   * @return {!proto.google.protobuf.Type} returns this
  */
  setSourceContext(value) {
    return jspb.Message.setWrapperField(this, 5, value);
  }


  /**
   * Clears the message field making it undefined.
   * @return {!proto.google.protobuf.Type} returns this
   */
  clearSourceContext() {
    return this.setSourceContext(undefined);
  };


  /**
   * Returns whether this field is set.
   * @return {boolean}
   */
  hasSourceContext() {
    return jspb.Message.getField(this, 5) != null;
  }


  /**
   * optional Syntax syntax = 6;
   * @return {!proto.google.protobuf.Syntax}
   */
  getSyntax() {
    return /** @type {!proto.google.protobuf.Syntax} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
  }

  /**
   * @param {!proto.google.protobuf.Syntax} value
   * @return {!proto.google.protobuf.Type} returns this
   */
  setSyntax(value) {
    return jspb.Message.setProto3EnumField(this, 6, value);
  }

  /**
   * optional string edition = 7;
   * @return {string}
   */
  getEdition() {
    return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
  }

  /**
   * @param {string} value
   * @return {!proto.google.protobuf.Type} returns this
   */
  setEdition(value) {
    return jspb.Message.setProto3StringField(this, 7, value);
  }

} // end class Type

/**
 * ES6 class generated by js_generator.cc.
 *
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
export class Field extends jspb.Message {
  /**
   * Generated by JsPbCodeGenerator.
   * @param {Array=} opt_data Optional initial data array, typically from a
   * server response, or constructed directly in Javascript. The array is used
   * in place and becomes part of the constructed object. It is not cloned.
   * If no data is provided, the constructed object will be empty, but still
   * valid.
   * @extends {jspb.Message}
   * @constructor
   */
  constructor(opt_data) {
    super(...arguments);
    jspb.Message.initialize(this, opt_data, 0, -1, Field.repeatedFields_, null);
  }

  /**
   * List of repeated fields within this message type.
   * @private {!Array<number>}
   * @const
   */
  static repeatedFields_ = [9];



  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  toObject(opt_includeInstance) {
    return Field.toObject(opt_includeInstance, this);
  }


  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!Field} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  static toObject(includeInstance, msg) {
    var f, obj = {
  kind: jspb.Message.getFieldWithDefault(msg, 1, 0),
  cardinality: jspb.Message.getFieldWithDefault(msg, 2, 0),
  number: jspb.Message.getFieldWithDefault(msg, 3, 0),
  name: jspb.Message.getFieldWithDefault(msg, 4, ""),
  typeUrl: jspb.Message.getFieldWithDefault(msg, 6, ""),
  oneofIndex: jspb.Message.getFieldWithDefault(msg, 7, 0),
  packed: jspb.Message.getBooleanFieldWithDefault(msg, 8, false),
  optionsList: jspb.Message.toObjectList(msg.getOptionsList(),
      Option.toObject, includeInstance),
  jsonName: jspb.Message.getFieldWithDefault(msg, 10, ""),
  defaultValue: jspb.Message.getFieldWithDefault(msg, 11, "")
    };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  }


  /**
   * Deserializes binary data (in protobuf wire format).
   * @param {jspb.binary.bytesource.ByteSource} bytes The bytes to deserialize.
   * @return {!Field}
   */
  static deserializeBinary(bytes) {
    var reader = new jspb.BinaryReader(bytes);
    var msg = new Field;
    return Field.deserializeBinaryFromReader(msg, reader);
  }


  /**
   * Deserializes binary data (in protobuf wire format) from the
   * given reader into the given message object.
   * @param {!Field} msg The message object to deserialize into.
   * @param {!jspb.BinaryReader} reader The BinaryReader to use.
   * @return {!Field}
   */
  static deserializeBinaryFromReader(msg, reader) {
    while (reader.nextField()) {
      if (reader.isEndGroup()) {
        break;
      }
      var field = reader.getFieldNumber();
      switch (field) {
      case 1:
        var value = /** @type {!proto.google.protobuf.Field.Kind} */ (reader.readEnum());
        msg.setKind(value);
        break;
      case 2:
        var value = /** @type {!proto.google.protobuf.Field.Cardinality} */ (reader.readEnum());
        msg.setCardinality(value);
        break;
      case 3:
        var value = /** @type {number} */ (reader.readInt32());
        msg.setNumber(value);
        break;
      case 4:
        var value = /** @type {string} */ (reader.readStringRequireUtf8());
        msg.setName(value);
        break;
      case 6:
        var value = /** @type {string} */ (reader.readStringRequireUtf8());
        msg.setTypeUrl(value);
        break;
      case 7:
        var value = /** @type {number} */ (reader.readInt32());
        msg.setOneofIndex(value);
        break;
      case 8:
        var value = /** @type {boolean} */ (reader.readBool());
        msg.setPacked(value);
        break;
      case 9:
        var value = new Option;
        reader.readMessage(value,Option.deserializeBinaryFromReader);
        msg.addOptions(value);
        break;
      case 10:
        var value = /** @type {string} */ (reader.readStringRequireUtf8());
        msg.setJsonName(value);
        break;
      case 11:
        var value = /** @type {string} */ (reader.readStringRequireUtf8());
        msg.setDefaultValue(value);
        break;
      default:
        reader.skipField();
        break;
      }
    }
    return msg;
  }


  /**
   * Serializes the message to binary data (in protobuf wire format).
   * @return {!Uint8Array}
   */
  serializeBinary() {
    var writer = new jspb.BinaryWriter();
    this.constructor.serializeBinaryToWriter(this, writer);
    return writer.getResultBuffer();
  }


  /**
   * Serializes the given message to binary data (in protobuf wire
   * format), writing to the given BinaryWriter.
   * @param {!Field} message
   * @param {!jspb.BinaryWriter} writer
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  static serializeBinaryToWriter(message, writer) {
    var f = undefined;
    f = message.getKind();
    if (f !== 0.0) {
      writer.writeEnum(
        1,
        f
      );
    }
    f = message.getCardinality();
    if (f !== 0.0) {
      writer.writeEnum(
        2,
        f
      );
    }
    f = message.getNumber();
    if (f !== 0) {
      writer.writeInt32(
        3,
        f
      );
    }
    f = message.getName();
    if (f.length > 0) {
      writer.writeString(
        4,
        f
      );
    }
    f = message.getTypeUrl();
    if (f.length > 0) {
      writer.writeString(
        6,
        f
      );
    }
    f = message.getOneofIndex();
    if (f !== 0) {
      writer.writeInt32(
        7,
        f
      );
    }
    f = message.getPacked();
    if (f) {
      writer.writeBool(
        8,
        f
      );
    }
    f = message.getOptionsList();
    if (f.length > 0) {
      writer.writeRepeatedMessage(
        9,
        f,
        Option.serializeBinaryToWriter
      );
    }
    f = message.getJsonName();
    if (f.length > 0) {
      writer.writeString(
        10,
        f
      );
    }
    f = message.getDefaultValue();
    if (f.length > 0) {
      writer.writeString(
        11,
        f
      );
    }
  }


  /**
   * @enum {number}
   */
  static Kind = {
    TYPE_UNKNOWN: 0,
    TYPE_DOUBLE: 1,
    TYPE_FLOAT: 2,
    TYPE_INT64: 3,
    TYPE_UINT64: 4,
    TYPE_INT32: 5,
    TYPE_FIXED64: 6,
    TYPE_FIXED32: 7,
    TYPE_BOOL: 8,
    TYPE_STRING: 9,
    TYPE_GROUP: 10,
    TYPE_MESSAGE: 11,
    TYPE_BYTES: 12,
    TYPE_UINT32: 13,
    TYPE_ENUM: 14,
    TYPE_SFIXED32: 15,
    TYPE_SFIXED64: 16,
    TYPE_SINT32: 17,
    TYPE_SINT64: 18
  };

  /**
   * @enum {number}
   */
  static Cardinality = {
    CARDINALITY_UNKNOWN: 0,
    CARDINALITY_OPTIONAL: 1,
    CARDINALITY_REQUIRED: 2,
    CARDINALITY_REPEATED: 3
  };

  /**
   * optional Kind kind = 1;
   * @return {!proto.google.protobuf.Field.Kind}
   */
  getKind() {
    return /** @type {!proto.google.protobuf.Field.Kind} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
  }

  /**
   * @param {!proto.google.protobuf.Field.Kind} value
   * @return {!proto.google.protobuf.Field} returns this
   */
  setKind(value) {
    return jspb.Message.setProto3EnumField(this, 1, value);
  }

  /**
   * optional Cardinality cardinality = 2;
   * @return {!proto.google.protobuf.Field.Cardinality}
   */
  getCardinality() {
    return /** @type {!proto.google.protobuf.Field.Cardinality} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
  }

  /**
   * @param {!proto.google.protobuf.Field.Cardinality} value
   * @return {!proto.google.protobuf.Field} returns this
   */
  setCardinality(value) {
    return jspb.Message.setProto3EnumField(this, 2, value);
  }

  /**
   * optional int32 number = 3;
   * @return {number}
   */
  getNumber() {
    return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
  }

  /**
   * @param {number} value
   * @return {!proto.google.protobuf.Field} returns this
   */
  setNumber(value) {
    return jspb.Message.setProto3IntField(this, 3, value);
  }

  /**
   * optional string name = 4;
   * @return {string}
   */
  getName() {
    return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
  }

  /**
   * @param {string} value
   * @return {!proto.google.protobuf.Field} returns this
   */
  setName(value) {
    return jspb.Message.setProto3StringField(this, 4, value);
  }

  /**
   * optional string type_url = 6;
   * @return {string}
   */
  getTypeUrl() {
    return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
  }

  /**
   * @param {string} value
   * @return {!proto.google.protobuf.Field} returns this
   */
  setTypeUrl(value) {
    return jspb.Message.setProto3StringField(this, 6, value);
  }

  /**
   * optional int32 oneof_index = 7;
   * @return {number}
   */
  getOneofIndex() {
    return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
  }

  /**
   * @param {number} value
   * @return {!proto.google.protobuf.Field} returns this
   */
  setOneofIndex(value) {
    return jspb.Message.setProto3IntField(this, 7, value);
  }

  /**
   * optional bool packed = 8;
   * @return {boolean}
   */
  getPacked() {
    return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 8, false));
  }

  /**
   * @param {boolean} value
   * @return {!proto.google.protobuf.Field} returns this
   */
  setPacked(value) {
    return jspb.Message.setProto3BooleanField(this, 8, value);
  }

  /**
   * repeated Option options = 9;
   * @return {!Array<!proto.google.protobuf.Option>}
   */
  getOptionsList() {
    return /** @type{!Array<!proto.google.protobuf.Option>} */ (
      jspb.Message.getRepeatedWrapperField(this, Option, 9));
  }


  /**
   * @param {!Array<!proto.google.protobuf.Option>} value
   * @return {!proto.google.protobuf.Field} returns this
  */
  setOptionsList(value) {
    return jspb.Message.setRepeatedWrapperField(this, 9, value);
  }


  /**
   * Adds a value to the repeated field fieldName 
   *
   * @param {!proto.google.protobuf.Option=} opt_value
   * @param {number=} opt_index
   * @return {!proto.google.protobuf.Option}
   */
  addOptions(opt_value, opt_index) {
    return jspb.Message.addToRepeatedWrapperField(this, 9, opt_value, Option, opt_index);
  };


  /**
   * Clears the list making it empty but non-null.
   * @return {!proto.google.protobuf.Field} returns this
   */
  clearOptionsList() {
    return this.setOptionsList([]);
  };


  /**
   * optional string json_name = 10;
   * @return {string}
   */
  getJsonName() {
    return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
  }

  /**
   * @param {string} value
   * @return {!proto.google.protobuf.Field} returns this
   */
  setJsonName(value) {
    return jspb.Message.setProto3StringField(this, 10, value);
  }

  /**
   * optional string default_value = 11;
   * @return {string}
   */
  getDefaultValue() {
    return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ""));
  }

  /**
   * @param {string} value
   * @return {!proto.google.protobuf.Field} returns this
   */
  setDefaultValue(value) {
    return jspb.Message.setProto3StringField(this, 11, value);
  }

} // end class Field

/**
 * ES6 class generated by js_generator.cc.
 *
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
export class Enum extends jspb.Message {
  /**
   * Generated by JsPbCodeGenerator.
   * @param {Array=} opt_data Optional initial data array, typically from a
   * server response, or constructed directly in Javascript. The array is used
   * in place and becomes part of the constructed object. It is not cloned.
   * If no data is provided, the constructed object will be empty, but still
   * valid.
   * @extends {jspb.Message}
   * @constructor
   */
  constructor(opt_data) {
    super(...arguments);
    jspb.Message.initialize(this, opt_data, 0, -1, Enum.repeatedFields_, null);
  }

  /**
   * List of repeated fields within this message type.
   * @private {!Array<number>}
   * @const
   */
  static repeatedFields_ = [2,3];



  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  toObject(opt_includeInstance) {
    return Enum.toObject(opt_includeInstance, this);
  }


  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!Enum} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  static toObject(includeInstance, msg) {
    var f, obj = {
  name: jspb.Message.getFieldWithDefault(msg, 1, ""),
  enumvalueList: jspb.Message.toObjectList(msg.getEnumvalueList(),
      EnumValue.toObject, includeInstance),
  optionsList: jspb.Message.toObjectList(msg.getOptionsList(),
      Option.toObject, includeInstance),
  sourceContext: (f = msg.getSourceContext()) && SourceContext.toObject(includeInstance, f),
  syntax: jspb.Message.getFieldWithDefault(msg, 5, 0),
  edition: jspb.Message.getFieldWithDefault(msg, 6, "")
    };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  }


  /**
   * Deserializes binary data (in protobuf wire format).
   * @param {jspb.binary.bytesource.ByteSource} bytes The bytes to deserialize.
   * @return {!Enum}
   */
  static deserializeBinary(bytes) {
    var reader = new jspb.BinaryReader(bytes);
    var msg = new Enum;
    return Enum.deserializeBinaryFromReader(msg, reader);
  }


  /**
   * Deserializes binary data (in protobuf wire format) from the
   * given reader into the given message object.
   * @param {!Enum} msg The message object to deserialize into.
   * @param {!jspb.BinaryReader} reader The BinaryReader to use.
   * @return {!Enum}
   */
  static deserializeBinaryFromReader(msg, reader) {
    while (reader.nextField()) {
      if (reader.isEndGroup()) {
        break;
      }
      var field = reader.getFieldNumber();
      switch (field) {
      case 1:
        var value = /** @type {string} */ (reader.readStringRequireUtf8());
        msg.setName(value);
        break;
      case 2:
        var value = new EnumValue;
        reader.readMessage(value,EnumValue.deserializeBinaryFromReader);
        msg.addEnumvalue(value);
        break;
      case 3:
        var value = new Option;
        reader.readMessage(value,Option.deserializeBinaryFromReader);
        msg.addOptions(value);
        break;
      case 4:
        var value = new SourceContext;
        reader.readMessage(value,SourceContext.deserializeBinaryFromReader);
        msg.setSourceContext(value);
        break;
      case 5:
        var value = /** @type {!proto.google.protobuf.Syntax} */ (reader.readEnum());
        msg.setSyntax(value);
        break;
      case 6:
        var value = /** @type {string} */ (reader.readStringRequireUtf8());
        msg.setEdition(value);
        break;
      default:
        reader.skipField();
        break;
      }
    }
    return msg;
  }


  /**
   * Serializes the message to binary data (in protobuf wire format).
   * @return {!Uint8Array}
   */
  serializeBinary() {
    var writer = new jspb.BinaryWriter();
    this.constructor.serializeBinaryToWriter(this, writer);
    return writer.getResultBuffer();
  }


  /**
   * Serializes the given message to binary data (in protobuf wire
   * format), writing to the given BinaryWriter.
   * @param {!Enum} message
   * @param {!jspb.BinaryWriter} writer
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  static serializeBinaryToWriter(message, writer) {
    var f = undefined;
    f = message.getName();
    if (f.length > 0) {
      writer.writeString(
        1,
        f
      );
    }
    f = message.getEnumvalueList();
    if (f.length > 0) {
      writer.writeRepeatedMessage(
        2,
        f,
        EnumValue.serializeBinaryToWriter
      );
    }
    f = message.getOptionsList();
    if (f.length > 0) {
      writer.writeRepeatedMessage(
        3,
        f,
        Option.serializeBinaryToWriter
      );
    }
    f = message.getSourceContext();
    if (f != null) {
      writer.writeMessage(
        4,
        f,
        SourceContext.serializeBinaryToWriter
      );
    }
    f = message.getSyntax();
    if (f !== 0.0) {
      writer.writeEnum(
        5,
        f
      );
    }
    f = message.getEdition();
    if (f.length > 0) {
      writer.writeString(
        6,
        f
      );
    }
  }


  /**
   * optional string name = 1;
   * @return {string}
   */
  getName() {
    return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
  }

  /**
   * @param {string} value
   * @return {!proto.google.protobuf.Enum} returns this
   */
  setName(value) {
    return jspb.Message.setProto3StringField(this, 1, value);
  }

  /**
   * repeated EnumValue enumvalue = 2;
   * @return {!Array<!proto.google.protobuf.EnumValue>}
   */
  getEnumvalueList() {
    return /** @type{!Array<!proto.google.protobuf.EnumValue>} */ (
      jspb.Message.getRepeatedWrapperField(this, EnumValue, 2));
  }


  /**
   * @param {!Array<!proto.google.protobuf.EnumValue>} value
   * @return {!proto.google.protobuf.Enum} returns this
  */
  setEnumvalueList(value) {
    return jspb.Message.setRepeatedWrapperField(this, 2, value);
  }


  /**
   * Adds a value to the repeated field fieldName 
   *
   * @param {!proto.google.protobuf.EnumValue=} opt_value
   * @param {number=} opt_index
   * @return {!proto.google.protobuf.EnumValue}
   */
  addEnumvalue(opt_value, opt_index) {
    return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, EnumValue, opt_index);
  };


  /**
   * Clears the list making it empty but non-null.
   * @return {!proto.google.protobuf.Enum} returns this
   */
  clearEnumvalueList() {
    return this.setEnumvalueList([]);
  };


  /**
   * repeated Option options = 3;
   * @return {!Array<!proto.google.protobuf.Option>}
   */
  getOptionsList() {
    return /** @type{!Array<!proto.google.protobuf.Option>} */ (
      jspb.Message.getRepeatedWrapperField(this, Option, 3));
  }


  /**
   * @param {!Array<!proto.google.protobuf.Option>} value
   * @return {!proto.google.protobuf.Enum} returns this
  */
  setOptionsList(value) {
    return jspb.Message.setRepeatedWrapperField(this, 3, value);
  }


  /**
   * Adds a value to the repeated field fieldName 
   *
   * @param {!proto.google.protobuf.Option=} opt_value
   * @param {number=} opt_index
   * @return {!proto.google.protobuf.Option}
   */
  addOptions(opt_value, opt_index) {
    return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, Option, opt_index);
  };


  /**
   * Clears the list making it empty but non-null.
   * @return {!proto.google.protobuf.Enum} returns this
   */
  clearOptionsList() {
    return this.setOptionsList([]);
  };


  /**
   * optional SourceContext source_context = 4;
   * @return {?proto.google.protobuf.SourceContext}
   */
  getSourceContext() {
    return /** @type{?proto.google.protobuf.SourceContext} */ (
      jspb.Message.getWrapperField(this, SourceContext, 4));
  }


  /**
   * @param {?proto.google.protobuf.SourceContext|undefined} value
   * @return {!proto.google.protobuf.Enum} returns this
  */
  setSourceContext(value) {
    return jspb.Message.setWrapperField(this, 4, value);
  }


  /**
   * Clears the message field making it undefined.
   * @return {!proto.google.protobuf.Enum} returns this
   */
  clearSourceContext() {
    return this.setSourceContext(undefined);
  };


  /**
   * Returns whether this field is set.
   * @return {boolean}
   */
  hasSourceContext() {
    return jspb.Message.getField(this, 4) != null;
  }


  /**
   * optional Syntax syntax = 5;
   * @return {!proto.google.protobuf.Syntax}
   */
  getSyntax() {
    return /** @type {!proto.google.protobuf.Syntax} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
  }

  /**
   * @param {!proto.google.protobuf.Syntax} value
   * @return {!proto.google.protobuf.Enum} returns this
   */
  setSyntax(value) {
    return jspb.Message.setProto3EnumField(this, 5, value);
  }

  /**
   * optional string edition = 6;
   * @return {string}
   */
  getEdition() {
    return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
  }

  /**
   * @param {string} value
   * @return {!proto.google.protobuf.Enum} returns this
   */
  setEdition(value) {
    return jspb.Message.setProto3StringField(this, 6, value);
  }

} // end class Enum

/**
 * ES6 class generated by js_generator.cc.
 *
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
export class EnumValue extends jspb.Message {
  /**
   * Generated by JsPbCodeGenerator.
   * @param {Array=} opt_data Optional initial data array, typically from a
   * server response, or constructed directly in Javascript. The array is used
   * in place and becomes part of the constructed object. It is not cloned.
   * If no data is provided, the constructed object will be empty, but still
   * valid.
   * @extends {jspb.Message}
   * @constructor
   */
  constructor(opt_data) {
    super(...arguments);
    jspb.Message.initialize(this, opt_data, 0, -1, EnumValue.repeatedFields_, null);
  }

  /**
   * List of repeated fields within this message type.
   * @private {!Array<number>}
   * @const
   */
  static repeatedFields_ = [3];



  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  toObject(opt_includeInstance) {
    return EnumValue.toObject(opt_includeInstance, this);
  }


  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!EnumValue} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  static toObject(includeInstance, msg) {
    var f, obj = {
  name: jspb.Message.getFieldWithDefault(msg, 1, ""),
  number: jspb.Message.getFieldWithDefault(msg, 2, 0),
  optionsList: jspb.Message.toObjectList(msg.getOptionsList(),
      Option.toObject, includeInstance)
    };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  }


  /**
   * Deserializes binary data (in protobuf wire format).
   * @param {jspb.binary.bytesource.ByteSource} bytes The bytes to deserialize.
   * @return {!EnumValue}
   */
  static deserializeBinary(bytes) {
    var reader = new jspb.BinaryReader(bytes);
    var msg = new EnumValue;
    return EnumValue.deserializeBinaryFromReader(msg, reader);
  }


  /**
   * Deserializes binary data (in protobuf wire format) from the
   * given reader into the given message object.
   * @param {!EnumValue} msg The message object to deserialize into.
   * @param {!jspb.BinaryReader} reader The BinaryReader to use.
   * @return {!EnumValue}
   */
  static deserializeBinaryFromReader(msg, reader) {
    while (reader.nextField()) {
      if (reader.isEndGroup()) {
        break;
      }
      var field = reader.getFieldNumber();
      switch (field) {
      case 1:
        var value = /** @type {string} */ (reader.readStringRequireUtf8());
        msg.setName(value);
        break;
      case 2:
        var value = /** @type {number} */ (reader.readInt32());
        msg.setNumber(value);
        break;
      case 3:
        var value = new Option;
        reader.readMessage(value,Option.deserializeBinaryFromReader);
        msg.addOptions(value);
        break;
      default:
        reader.skipField();
        break;
      }
    }
    return msg;
  }


  /**
   * Serializes the message to binary data (in protobuf wire format).
   * @return {!Uint8Array}
   */
  serializeBinary() {
    var writer = new jspb.BinaryWriter();
    this.constructor.serializeBinaryToWriter(this, writer);
    return writer.getResultBuffer();
  }


  /**
   * Serializes the given message to binary data (in protobuf wire
   * format), writing to the given BinaryWriter.
   * @param {!EnumValue} message
   * @param {!jspb.BinaryWriter} writer
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  static serializeBinaryToWriter(message, writer) {
    var f = undefined;
    f = message.getName();
    if (f.length > 0) {
      writer.writeString(
        1,
        f
      );
    }
    f = message.getNumber();
    if (f !== 0) {
      writer.writeInt32(
        2,
        f
      );
    }
    f = message.getOptionsList();
    if (f.length > 0) {
      writer.writeRepeatedMessage(
        3,
        f,
        Option.serializeBinaryToWriter
      );
    }
  }


  /**
   * optional string name = 1;
   * @return {string}
   */
  getName() {
    return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
  }

  /**
   * @param {string} value
   * @return {!proto.google.protobuf.EnumValue} returns this
   */
  setName(value) {
    return jspb.Message.setProto3StringField(this, 1, value);
  }

  /**
   * optional int32 number = 2;
   * @return {number}
   */
  getNumber() {
    return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
  }

  /**
   * @param {number} value
   * @return {!proto.google.protobuf.EnumValue} returns this
   */
  setNumber(value) {
    return jspb.Message.setProto3IntField(this, 2, value);
  }

  /**
   * repeated Option options = 3;
   * @return {!Array<!proto.google.protobuf.Option>}
   */
  getOptionsList() {
    return /** @type{!Array<!proto.google.protobuf.Option>} */ (
      jspb.Message.getRepeatedWrapperField(this, Option, 3));
  }


  /**
   * @param {!Array<!proto.google.protobuf.Option>} value
   * @return {!proto.google.protobuf.EnumValue} returns this
  */
  setOptionsList(value) {
    return jspb.Message.setRepeatedWrapperField(this, 3, value);
  }


  /**
   * Adds a value to the repeated field fieldName 
   *
   * @param {!proto.google.protobuf.Option=} opt_value
   * @param {number=} opt_index
   * @return {!proto.google.protobuf.Option}
   */
  addOptions(opt_value, opt_index) {
    return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, Option, opt_index);
  };


  /**
   * Clears the list making it empty but non-null.
   * @return {!proto.google.protobuf.EnumValue} returns this
   */
  clearOptionsList() {
    return this.setOptionsList([]);
  };


} // end class EnumValue

/**
 * ES6 class generated by js_generator.cc.
 *
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
export class Option extends jspb.Message {
  /**
   * Generated by JsPbCodeGenerator.
   * @param {Array=} opt_data Optional initial data array, typically from a
   * server response, or constructed directly in Javascript. The array is used
   * in place and becomes part of the constructed object. It is not cloned.
   * If no data is provided, the constructed object will be empty, but still
   * valid.
   * @extends {jspb.Message}
   * @constructor
   */
  constructor(opt_data) {
    super(...arguments);
    jspb.Message.initialize(this, opt_data, 0, -1, null, null);
  }



  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  toObject(opt_includeInstance) {
    return Option.toObject(opt_includeInstance, this);
  }


  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!Option} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  static toObject(includeInstance, msg) {
    var f, obj = {
  name: jspb.Message.getFieldWithDefault(msg, 1, ""),
  value: (f = msg.getValue()) && Any.toObject(includeInstance, f)
    };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  }


  /**
   * Deserializes binary data (in protobuf wire format).
   * @param {jspb.binary.bytesource.ByteSource} bytes The bytes to deserialize.
   * @return {!Option}
   */
  static deserializeBinary(bytes) {
    var reader = new jspb.BinaryReader(bytes);
    var msg = new Option;
    return Option.deserializeBinaryFromReader(msg, reader);
  }


  /**
   * Deserializes binary data (in protobuf wire format) from the
   * given reader into the given message object.
   * @param {!Option} msg The message object to deserialize into.
   * @param {!jspb.BinaryReader} reader The BinaryReader to use.
   * @return {!Option}
   */
  static deserializeBinaryFromReader(msg, reader) {
    while (reader.nextField()) {
      if (reader.isEndGroup()) {
        break;
      }
      var field = reader.getFieldNumber();
      switch (field) {
      case 1:
        var value = /** @type {string} */ (reader.readStringRequireUtf8());
        msg.setName(value);
        break;
      case 2:
        var value = new Any;
        reader.readMessage(value,Any.deserializeBinaryFromReader);
        msg.setValue(value);
        break;
      default:
        reader.skipField();
        break;
      }
    }
    return msg;
  }


  /**
   * Serializes the message to binary data (in protobuf wire format).
   * @return {!Uint8Array}
   */
  serializeBinary() {
    var writer = new jspb.BinaryWriter();
    this.constructor.serializeBinaryToWriter(this, writer);
    return writer.getResultBuffer();
  }


  /**
   * Serializes the given message to binary data (in protobuf wire
   * format), writing to the given BinaryWriter.
   * @param {!Option} message
   * @param {!jspb.BinaryWriter} writer
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  static serializeBinaryToWriter(message, writer) {
    var f = undefined;
    f = message.getName();
    if (f.length > 0) {
      writer.writeString(
        1,
        f
      );
    }
    f = message.getValue();
    if (f != null) {
      writer.writeMessage(
        2,
        f,
        Any.serializeBinaryToWriter
      );
    }
  }


  /**
   * optional string name = 1;
   * @return {string}
   */
  getName() {
    return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
  }

  /**
   * @param {string} value
   * @return {!proto.google.protobuf.Option} returns this
   */
  setName(value) {
    return jspb.Message.setProto3StringField(this, 1, value);
  }

  /**
   * optional Any value = 2;
   * @return {?proto.google.protobuf.Any}
   */
  getValue() {
    return /** @type{?proto.google.protobuf.Any} */ (
      jspb.Message.getWrapperField(this, Any, 2));
  }


  /**
   * @param {?proto.google.protobuf.Any|undefined} value
   * @return {!proto.google.protobuf.Option} returns this
  */
  setValue(value) {
    return jspb.Message.setWrapperField(this, 2, value);
  }


  /**
   * Clears the message field making it undefined.
   * @return {!proto.google.protobuf.Option} returns this
   */
  clearValue() {
    return this.setValue(undefined);
  };


  /**
   * Returns whether this field is set.
   * @return {boolean}
   */
  hasValue() {
    return jspb.Message.getField(this, 2) != null;
  }


} // end class Option
/**
 * @enum {number}
 */
export const Syntax = {
  SYNTAX_PROTO2: 0,
  SYNTAX_PROTO3: 1,
  SYNTAX_EDITIONS: 2
};

