// source: google/protobuf/compiler/plugin.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

import jspb from "google-protobuf";
import {FileDescriptorSet, FileDescriptorProto, DescriptorProto, ExtensionRangeOptions, FieldDescriptorProto, OneofDescriptorProto, EnumDescriptorProto, EnumValueDescriptorProto, ServiceDescriptorProto, MethodDescriptorProto, FileOptions, MessageOptions, FieldOptions, OneofOptions, EnumOptions, EnumValueOptions, ServiceOptions, MethodOptions, UninterpretedOption, FeatureSet, FeatureSetDefaults, SourceCodeInfo, GeneratedCodeInfo, Edition, SymbolVisibility} from "google-protobuf/google/protobuf/descriptor_pb.mjs"; // proto import: "google/protobuf/descriptor.proto"

/**
 * ES6 class generated by js_generator.cc.
 *
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
export class Version extends jspb.Message {
  /**
   * Generated by JsPbCodeGenerator.
   * @param {Array=} opt_data Optional initial data array, typically from a
   * server response, or constructed directly in Javascript. The array is used
   * in place and becomes part of the constructed object. It is not cloned.
   * If no data is provided, the constructed object will be empty, but still
   * valid.
   * @extends {jspb.Message}
   * @constructor
   */
  constructor(opt_data) {
    super(...arguments);
    jspb.Message.initialize(this, opt_data, 0, -1, null, null);
  }



  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  toObject(opt_includeInstance) {
    return Version.toObject(opt_includeInstance, this);
  }


  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!Version} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  static toObject(includeInstance, msg) {
    var f, obj = {
  major: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
  minor: (f = jspb.Message.getField(msg, 2)) == null ? undefined : f,
  patch: (f = jspb.Message.getField(msg, 3)) == null ? undefined : f,
  suffix: (f = jspb.Message.getField(msg, 4)) == null ? undefined : f
    };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  }


  /**
   * Deserializes binary data (in protobuf wire format).
   * @param {jspb.binary.bytesource.ByteSource} bytes The bytes to deserialize.
   * @return {!Version}
   */
  static deserializeBinary(bytes) {
    var reader = new jspb.BinaryReader(bytes);
    var msg = new Version;
    return Version.deserializeBinaryFromReader(msg, reader);
  }


  /**
   * Deserializes binary data (in protobuf wire format) from the
   * given reader into the given message object.
   * @param {!Version} msg The message object to deserialize into.
   * @param {!jspb.BinaryReader} reader The BinaryReader to use.
   * @return {!Version}
   */
  static deserializeBinaryFromReader(msg, reader) {
    while (reader.nextField()) {
      if (reader.isEndGroup()) {
        break;
      }
      var field = reader.getFieldNumber();
      switch (field) {
      case 1:
        var value = /** @type {number} */ (reader.readInt32());
        msg.setMajor(value);
        break;
      case 2:
        var value = /** @type {number} */ (reader.readInt32());
        msg.setMinor(value);
        break;
      case 3:
        var value = /** @type {number} */ (reader.readInt32());
        msg.setPatch(value);
        break;
      case 4:
        var value = /** @type {string} */ (reader.readString());
        msg.setSuffix(value);
        break;
      default:
        reader.skipField();
        break;
      }
    }
    return msg;
  }


  /**
   * Serializes the message to binary data (in protobuf wire format).
   * @return {!Uint8Array}
   */
  serializeBinary() {
    var writer = new jspb.BinaryWriter();
    this.constructor.serializeBinaryToWriter(this, writer);
    return writer.getResultBuffer();
  }


  /**
   * Serializes the given message to binary data (in protobuf wire
   * format), writing to the given BinaryWriter.
   * @param {!Version} message
   * @param {!jspb.BinaryWriter} writer
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  static serializeBinaryToWriter(message, writer) {
    var f = undefined;
    f = /** @type {number} */ (jspb.Message.getField(message, 1));
    if (f != null) {
      writer.writeInt32(
        1,
        f
      );
    }
    f = /** @type {number} */ (jspb.Message.getField(message, 2));
    if (f != null) {
      writer.writeInt32(
        2,
        f
      );
    }
    f = /** @type {number} */ (jspb.Message.getField(message, 3));
    if (f != null) {
      writer.writeInt32(
        3,
        f
      );
    }
    f = /** @type {string} */ (jspb.Message.getField(message, 4));
    if (f != null) {
      writer.writeString(
        4,
        f
      );
    }
  }


  /**
   * optional int32 major = 1;
   * @return {number}
   */
  getMajor() {
    return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
  }

  /**
   * @param {number} value
   * @return {!proto.google.protobuf.compiler.Version} returns this
   */
  setMajor(value) {
    return jspb.Message.setField(this, 1, value);
  };


  /**
   * Clears the field making it undefined.
   * @return {!proto.google.protobuf.compiler.Version} returns this
   */
  clearMajor() {
    return jspb.Message.setField(this, 1, undefined);
  };


  /**
   * Returns whether this field is set.
   * @return {boolean}
   */
  hasMajor() {
    return jspb.Message.getField(this, 1) != null;
  }


  /**
   * optional int32 minor = 2;
   * @return {number}
   */
  getMinor() {
    return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
  }

  /**
   * @param {number} value
   * @return {!proto.google.protobuf.compiler.Version} returns this
   */
  setMinor(value) {
    return jspb.Message.setField(this, 2, value);
  };


  /**
   * Clears the field making it undefined.
   * @return {!proto.google.protobuf.compiler.Version} returns this
   */
  clearMinor() {
    return jspb.Message.setField(this, 2, undefined);
  };


  /**
   * Returns whether this field is set.
   * @return {boolean}
   */
  hasMinor() {
    return jspb.Message.getField(this, 2) != null;
  }


  /**
   * optional int32 patch = 3;
   * @return {number}
   */
  getPatch() {
    return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
  }

  /**
   * @param {number} value
   * @return {!proto.google.protobuf.compiler.Version} returns this
   */
  setPatch(value) {
    return jspb.Message.setField(this, 3, value);
  };


  /**
   * Clears the field making it undefined.
   * @return {!proto.google.protobuf.compiler.Version} returns this
   */
  clearPatch() {
    return jspb.Message.setField(this, 3, undefined);
  };


  /**
   * Returns whether this field is set.
   * @return {boolean}
   */
  hasPatch() {
    return jspb.Message.getField(this, 3) != null;
  }


  /**
   * optional string suffix = 4;
   * @return {string}
   */
  getSuffix() {
    return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
  }

  /**
   * @param {string} value
   * @return {!proto.google.protobuf.compiler.Version} returns this
   */
  setSuffix(value) {
    return jspb.Message.setField(this, 4, value);
  };


  /**
   * Clears the field making it undefined.
   * @return {!proto.google.protobuf.compiler.Version} returns this
   */
  clearSuffix() {
    return jspb.Message.setField(this, 4, undefined);
  };


  /**
   * Returns whether this field is set.
   * @return {boolean}
   */
  hasSuffix() {
    return jspb.Message.getField(this, 4) != null;
  }


} // end class Version

/**
 * ES6 class generated by js_generator.cc.
 *
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
export class CodeGeneratorRequest extends jspb.Message {
  /**
   * Generated by JsPbCodeGenerator.
   * @param {Array=} opt_data Optional initial data array, typically from a
   * server response, or constructed directly in Javascript. The array is used
   * in place and becomes part of the constructed object. It is not cloned.
   * If no data is provided, the constructed object will be empty, but still
   * valid.
   * @extends {jspb.Message}
   * @constructor
   */
  constructor(opt_data) {
    super(...arguments);
    jspb.Message.initialize(this, opt_data, 0, -1, CodeGeneratorRequest.repeatedFields_, null);
  }

  /**
   * List of repeated fields within this message type.
   * @private {!Array<number>}
   * @const
   */
  static repeatedFields_ = [1,15,17];



  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  toObject(opt_includeInstance) {
    return CodeGeneratorRequest.toObject(opt_includeInstance, this);
  }


  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!CodeGeneratorRequest} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  static toObject(includeInstance, msg) {
    var f, obj = {
  fileToGenerateList: (f = jspb.Message.getRepeatedField(msg, 1)) == null ? undefined : f,
  parameter: (f = jspb.Message.getField(msg, 2)) == null ? undefined : f,
  protoFileList: jspb.Message.toObjectList(msg.getProtoFileList(),
      FileDescriptorProto.toObject, includeInstance),
  sourceFileDescriptorsList: jspb.Message.toObjectList(msg.getSourceFileDescriptorsList(),
      FileDescriptorProto.toObject, includeInstance),
  compilerVersion: (f = msg.getCompilerVersion()) && Version.toObject(includeInstance, f)
    };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  }


  /**
   * Deserializes binary data (in protobuf wire format).
   * @param {jspb.binary.bytesource.ByteSource} bytes The bytes to deserialize.
   * @return {!CodeGeneratorRequest}
   */
  static deserializeBinary(bytes) {
    var reader = new jspb.BinaryReader(bytes);
    var msg = new CodeGeneratorRequest;
    return CodeGeneratorRequest.deserializeBinaryFromReader(msg, reader);
  }


  /**
   * Deserializes binary data (in protobuf wire format) from the
   * given reader into the given message object.
   * @param {!CodeGeneratorRequest} msg The message object to deserialize into.
   * @param {!jspb.BinaryReader} reader The BinaryReader to use.
   * @return {!CodeGeneratorRequest}
   */
  static deserializeBinaryFromReader(msg, reader) {
    while (reader.nextField()) {
      if (reader.isEndGroup()) {
        break;
      }
      var field = reader.getFieldNumber();
      switch (field) {
      case 1:
        var value = /** @type {string} */ (reader.readString());
        msg.addFileToGenerate(value);
        break;
      case 2:
        var value = /** @type {string} */ (reader.readString());
        msg.setParameter(value);
        break;
      case 15:
        var value = new FileDescriptorProto;
        reader.readMessage(value,FileDescriptorProto.deserializeBinaryFromReader);
        msg.addProtoFile(value);
        break;
      case 17:
        var value = new FileDescriptorProto;
        reader.readMessage(value,FileDescriptorProto.deserializeBinaryFromReader);
        msg.addSourceFileDescriptors(value);
        break;
      case 3:
        var value = new Version;
        reader.readMessage(value,Version.deserializeBinaryFromReader);
        msg.setCompilerVersion(value);
        break;
      default:
        reader.skipField();
        break;
      }
    }
    return msg;
  }


  /**
   * Serializes the message to binary data (in protobuf wire format).
   * @return {!Uint8Array}
   */
  serializeBinary() {
    var writer = new jspb.BinaryWriter();
    this.constructor.serializeBinaryToWriter(this, writer);
    return writer.getResultBuffer();
  }


  /**
   * Serializes the given message to binary data (in protobuf wire
   * format), writing to the given BinaryWriter.
   * @param {!CodeGeneratorRequest} message
   * @param {!jspb.BinaryWriter} writer
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  static serializeBinaryToWriter(message, writer) {
    var f = undefined;
    f = message.getFileToGenerateList();
    if (f.length > 0) {
      writer.writeRepeatedString(
        1,
        f
      );
    }
    f = /** @type {string} */ (jspb.Message.getField(message, 2));
    if (f != null) {
      writer.writeString(
        2,
        f
      );
    }
    f = message.getProtoFileList();
    if (f.length > 0) {
      writer.writeRepeatedMessage(
        15,
        f,
        FileDescriptorProto.serializeBinaryToWriter
      );
    }
    f = message.getSourceFileDescriptorsList();
    if (f.length > 0) {
      writer.writeRepeatedMessage(
        17,
        f,
        FileDescriptorProto.serializeBinaryToWriter
      );
    }
    f = message.getCompilerVersion();
    if (f != null) {
      writer.writeMessage(
        3,
        f,
        Version.serializeBinaryToWriter
      );
    }
  }


  /**
   * repeated string file_to_generate = 1;
   * @return {!Array<string>}
   */
  getFileToGenerateList() {
    return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 1));
  }

  /**
   * @param {!Array<string>} value
   * @return {!proto.google.protobuf.compiler.CodeGeneratorRequest} returns this
   */
  setFileToGenerateList(value) {
    return jspb.Message.setField(this, 1, value || []);
  };


  /**
   * Adds a value to the repeated field addFileToGenerate 
   *
   * @param {string} value
   * @param {number=} opt_index
   * @return {!proto.google.protobuf.compiler.CodeGeneratorRequest} returns this
   */
  addFileToGenerate(value, opt_index) {
    return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
  };


  /**
   * Clears the list making it empty but non-null.
   * @return {!proto.google.protobuf.compiler.CodeGeneratorRequest} returns this
   */
  clearFileToGenerateList() {
    return this.setFileToGenerateList([]);
  };


  /**
   * optional string parameter = 2;
   * @return {string}
   */
  getParameter() {
    return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
  }

  /**
   * @param {string} value
   * @return {!proto.google.protobuf.compiler.CodeGeneratorRequest} returns this
   */
  setParameter(value) {
    return jspb.Message.setField(this, 2, value);
  };


  /**
   * Clears the field making it undefined.
   * @return {!proto.google.protobuf.compiler.CodeGeneratorRequest} returns this
   */
  clearParameter() {
    return jspb.Message.setField(this, 2, undefined);
  };


  /**
   * Returns whether this field is set.
   * @return {boolean}
   */
  hasParameter() {
    return jspb.Message.getField(this, 2) != null;
  }


  /**
   * repeated google.protobuf.FileDescriptorProto proto_file = 15;
   * @return {!Array<!proto.google.protobuf.FileDescriptorProto>}
   */
  getProtoFileList() {
    return /** @type{!Array<!proto.google.protobuf.FileDescriptorProto>} */ (
      jspb.Message.getRepeatedWrapperField(this, FileDescriptorProto, 15));
  }


  /**
   * @param {!Array<!proto.google.protobuf.FileDescriptorProto>} value
   * @return {!proto.google.protobuf.compiler.CodeGeneratorRequest} returns this
  */
  setProtoFileList(value) {
    return jspb.Message.setRepeatedWrapperField(this, 15, value);
  }


  /**
   * Adds a value to the repeated field fieldName 
   *
   * @param {!proto.google.protobuf.FileDescriptorProto=} opt_value
   * @param {number=} opt_index
   * @return {!proto.google.protobuf.FileDescriptorProto}
   */
  addProtoFile(opt_value, opt_index) {
    return jspb.Message.addToRepeatedWrapperField(this, 15, opt_value, FileDescriptorProto, opt_index);
  };


  /**
   * Clears the list making it empty but non-null.
   * @return {!proto.google.protobuf.compiler.CodeGeneratorRequest} returns this
   */
  clearProtoFileList() {
    return this.setProtoFileList([]);
  };


  /**
   * repeated google.protobuf.FileDescriptorProto source_file_descriptors = 17;
   * @return {!Array<!proto.google.protobuf.FileDescriptorProto>}
   */
  getSourceFileDescriptorsList() {
    return /** @type{!Array<!proto.google.protobuf.FileDescriptorProto>} */ (
      jspb.Message.getRepeatedWrapperField(this, FileDescriptorProto, 17));
  }


  /**
   * @param {!Array<!proto.google.protobuf.FileDescriptorProto>} value
   * @return {!proto.google.protobuf.compiler.CodeGeneratorRequest} returns this
  */
  setSourceFileDescriptorsList(value) {
    return jspb.Message.setRepeatedWrapperField(this, 17, value);
  }


  /**
   * Adds a value to the repeated field fieldName 
   *
   * @param {!proto.google.protobuf.FileDescriptorProto=} opt_value
   * @param {number=} opt_index
   * @return {!proto.google.protobuf.FileDescriptorProto}
   */
  addSourceFileDescriptors(opt_value, opt_index) {
    return jspb.Message.addToRepeatedWrapperField(this, 17, opt_value, FileDescriptorProto, opt_index);
  };


  /**
   * Clears the list making it empty but non-null.
   * @return {!proto.google.protobuf.compiler.CodeGeneratorRequest} returns this
   */
  clearSourceFileDescriptorsList() {
    return this.setSourceFileDescriptorsList([]);
  };


  /**
   * optional Version compiler_version = 3;
   * @return {?proto.google.protobuf.compiler.Version}
   */
  getCompilerVersion() {
    return /** @type{?proto.google.protobuf.compiler.Version} */ (
      jspb.Message.getWrapperField(this, Version, 3));
  }


  /**
   * @param {?proto.google.protobuf.compiler.Version|undefined} value
   * @return {!proto.google.protobuf.compiler.CodeGeneratorRequest} returns this
  */
  setCompilerVersion(value) {
    return jspb.Message.setWrapperField(this, 3, value);
  }


  /**
   * Clears the message field making it undefined.
   * @return {!proto.google.protobuf.compiler.CodeGeneratorRequest} returns this
   */
  clearCompilerVersion() {
    return this.setCompilerVersion(undefined);
  };


  /**
   * Returns whether this field is set.
   * @return {boolean}
   */
  hasCompilerVersion() {
    return jspb.Message.getField(this, 3) != null;
  }


} // end class CodeGeneratorRequest

/**
 * ES6 class generated by js_generator.cc.
 *
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
export class CodeGeneratorResponse extends jspb.Message {
  /**
   * Generated by JsPbCodeGenerator.
   * @param {Array=} opt_data Optional initial data array, typically from a
   * server response, or constructed directly in Javascript. The array is used
   * in place and becomes part of the constructed object. It is not cloned.
   * If no data is provided, the constructed object will be empty, but still
   * valid.
   * @extends {jspb.Message}
   * @constructor
   */
  constructor(opt_data) {
    super(...arguments);
    jspb.Message.initialize(this, opt_data, 0, -1, CodeGeneratorResponse.repeatedFields_, null);
  }

  /**
   * List of repeated fields within this message type.
   * @private {!Array<number>}
   * @const
   */
  static repeatedFields_ = [15];



  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  toObject(opt_includeInstance) {
    return CodeGeneratorResponse.toObject(opt_includeInstance, this);
  }


  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!CodeGeneratorResponse} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  static toObject(includeInstance, msg) {
    var f, obj = {
  error: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
  supportedFeatures: (f = jspb.Message.getField(msg, 2)) == null ? undefined : f,
  minimumEdition: (f = jspb.Message.getField(msg, 3)) == null ? undefined : f,
  maximumEdition: (f = jspb.Message.getField(msg, 4)) == null ? undefined : f,
  fileList: jspb.Message.toObjectList(msg.getFileList(),
      CodeGeneratorResponse.File.toObject, includeInstance)
    };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  }


  /**
   * Deserializes binary data (in protobuf wire format).
   * @param {jspb.binary.bytesource.ByteSource} bytes The bytes to deserialize.
   * @return {!CodeGeneratorResponse}
   */
  static deserializeBinary(bytes) {
    var reader = new jspb.BinaryReader(bytes);
    var msg = new CodeGeneratorResponse;
    return CodeGeneratorResponse.deserializeBinaryFromReader(msg, reader);
  }


  /**
   * Deserializes binary data (in protobuf wire format) from the
   * given reader into the given message object.
   * @param {!CodeGeneratorResponse} msg The message object to deserialize into.
   * @param {!jspb.BinaryReader} reader The BinaryReader to use.
   * @return {!CodeGeneratorResponse}
   */
  static deserializeBinaryFromReader(msg, reader) {
    while (reader.nextField()) {
      if (reader.isEndGroup()) {
        break;
      }
      var field = reader.getFieldNumber();
      switch (field) {
      case 1:
        var value = /** @type {string} */ (reader.readString());
        msg.setError(value);
        break;
      case 2:
        var value = /** @type {number} */ (reader.readUint64());
        msg.setSupportedFeatures(value);
        break;
      case 3:
        var value = /** @type {number} */ (reader.readInt32());
        msg.setMinimumEdition(value);
        break;
      case 4:
        var value = /** @type {number} */ (reader.readInt32());
        msg.setMaximumEdition(value);
        break;
      case 15:
        var value = new CodeGeneratorResponse.File;
        reader.readMessage(value,CodeGeneratorResponse.File.deserializeBinaryFromReader);
        msg.addFile(value);
        break;
      default:
        reader.skipField();
        break;
      }
    }
    return msg;
  }


  /**
   * Serializes the message to binary data (in protobuf wire format).
   * @return {!Uint8Array}
   */
  serializeBinary() {
    var writer = new jspb.BinaryWriter();
    this.constructor.serializeBinaryToWriter(this, writer);
    return writer.getResultBuffer();
  }


  /**
   * Serializes the given message to binary data (in protobuf wire
   * format), writing to the given BinaryWriter.
   * @param {!CodeGeneratorResponse} message
   * @param {!jspb.BinaryWriter} writer
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  static serializeBinaryToWriter(message, writer) {
    var f = undefined;
    f = /** @type {string} */ (jspb.Message.getField(message, 1));
    if (f != null) {
      writer.writeString(
        1,
        f
      );
    }
    f = /** @type {number} */ (jspb.Message.getField(message, 2));
    if (f != null) {
      writer.writeUint64(
        2,
        f
      );
    }
    f = /** @type {number} */ (jspb.Message.getField(message, 3));
    if (f != null) {
      writer.writeInt32(
        3,
        f
      );
    }
    f = /** @type {number} */ (jspb.Message.getField(message, 4));
    if (f != null) {
      writer.writeInt32(
        4,
        f
      );
    }
    f = message.getFileList();
    if (f.length > 0) {
      writer.writeRepeatedMessage(
        15,
        f,
        CodeGeneratorResponse.File.serializeBinaryToWriter
      );
    }
  }


  /**
   * @enum {number}
   */
  static Feature = {
    FEATURE_NONE: 0,
    FEATURE_PROTO3_OPTIONAL: 1,
    FEATURE_SUPPORTS_EDITIONS: 2
  };


  /**
   * ES6 class generated by js_generator.cc.
   *
   * @param {Array=} opt_data Optional initial data array, typically from a
   * server response, or constructed directly in Javascript. The array is used
   * in place and becomes part of the constructed object. It is not cloned.
   * If no data is provided, the constructed object will be empty, but still
   * valid.
   * @extends {jspb.Message}
   * @constructor
   */
  static File = class File extends jspb.Message {
    /**
     * Generated by JsPbCodeGenerator.
     * @param {Array=} opt_data Optional initial data array, typically from a
     * server response, or constructed directly in Javascript. The array is used
     * in place and becomes part of the constructed object. It is not cloned.
     * If no data is provided, the constructed object will be empty, but still
     * valid.
     * @extends {jspb.Message}
     * @constructor
     */
    constructor(opt_data) {
      super(...arguments);
      jspb.Message.initialize(this, opt_data, 0, -1, null, null);
    }



    /**
     * Creates an object representation of this proto.
     * Field names that are reserved in JavaScript and will be renamed to pb_name.
     * Optional fields that are not set will be set to undefined.
     * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
     * For the list of reserved names please see:
     *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
     * @param {boolean=} opt_includeInstance Deprecated. whether to include the
     *     JSPB instance for transitional soy proto support:
     *     http://goto/soy-param-migration
     * @return {!Object}
     */
    toObject(opt_includeInstance) {
      return File.toObject(opt_includeInstance, this);
    }


    /**
     * Static version of the {@see toObject} method.
     * @param {boolean|undefined} includeInstance Deprecated. Whether to include
     *     the JSPB instance for transitional soy proto support:
     *     http://goto/soy-param-migration
     * @param {!File} msg The msg instance to transform.
     * @return {!Object}
     * @suppress {unusedLocalVariables} f is only used for nested messages
     */
    static toObject(includeInstance, msg) {
      var f, obj = {
    name: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
    insertionPoint: (f = jspb.Message.getField(msg, 2)) == null ? undefined : f,
    content: (f = jspb.Message.getField(msg, 15)) == null ? undefined : f,
    generatedCodeInfo: (f = msg.getGeneratedCodeInfo()) && GeneratedCodeInfo.toObject(includeInstance, f)
      };

      if (includeInstance) {
        obj.$jspbMessageInstance = msg;
      }
      return obj;
    }


    /**
     * Deserializes binary data (in protobuf wire format).
     * @param {jspb.binary.bytesource.ByteSource} bytes The bytes to deserialize.
     * @return {!File}
     */
    static deserializeBinary(bytes) {
      var reader = new jspb.BinaryReader(bytes);
      var msg = new File;
      return File.deserializeBinaryFromReader(msg, reader);
    }


    /**
     * Deserializes binary data (in protobuf wire format) from the
     * given reader into the given message object.
     * @param {!File} msg The message object to deserialize into.
     * @param {!jspb.BinaryReader} reader The BinaryReader to use.
     * @return {!File}
     */
    static deserializeBinaryFromReader(msg, reader) {
      while (reader.nextField()) {
        if (reader.isEndGroup()) {
          break;
        }
        var field = reader.getFieldNumber();
        switch (field) {
        case 1:
          var value = /** @type {string} */ (reader.readString());
          msg.setName(value);
          break;
        case 2:
          var value = /** @type {string} */ (reader.readString());
          msg.setInsertionPoint(value);
          break;
        case 15:
          var value = /** @type {string} */ (reader.readString());
          msg.setContent(value);
          break;
        case 16:
          var value = new GeneratedCodeInfo;
          reader.readMessage(value,GeneratedCodeInfo.deserializeBinaryFromReader);
          msg.setGeneratedCodeInfo(value);
          break;
        default:
          reader.skipField();
          break;
        }
      }
      return msg;
    }


    /**
     * Serializes the message to binary data (in protobuf wire format).
     * @return {!Uint8Array}
     */
    serializeBinary() {
      var writer = new jspb.BinaryWriter();
      this.constructor.serializeBinaryToWriter(this, writer);
      return writer.getResultBuffer();
    }


    /**
     * Serializes the given message to binary data (in protobuf wire
     * format), writing to the given BinaryWriter.
     * @param {!File} message
     * @param {!jspb.BinaryWriter} writer
     * @suppress {unusedLocalVariables} f is only used for nested messages
     */
    static serializeBinaryToWriter(message, writer) {
      var f = undefined;
      f = /** @type {string} */ (jspb.Message.getField(message, 1));
      if (f != null) {
        writer.writeString(
          1,
          f
        );
      }
      f = /** @type {string} */ (jspb.Message.getField(message, 2));
      if (f != null) {
        writer.writeString(
          2,
          f
        );
      }
      f = /** @type {string} */ (jspb.Message.getField(message, 15));
      if (f != null) {
        writer.writeString(
          15,
          f
        );
      }
      f = message.getGeneratedCodeInfo();
      if (f != null) {
        writer.writeMessage(
          16,
          f,
          GeneratedCodeInfo.serializeBinaryToWriter
        );
      }
    }


    /**
     * optional string name = 1;
     * @return {string}
     */
    getName() {
      return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
    }

    /**
     * @param {string} value
     * @return {!proto.google.protobuf.compiler.CodeGeneratorResponse.File} returns this
     */
    setName(value) {
      return jspb.Message.setField(this, 1, value);
    };


    /**
     * Clears the field making it undefined.
     * @return {!proto.google.protobuf.compiler.CodeGeneratorResponse.File} returns this
     */
    clearName() {
      return jspb.Message.setField(this, 1, undefined);
    };


    /**
     * Returns whether this field is set.
     * @return {boolean}
     */
    hasName() {
      return jspb.Message.getField(this, 1) != null;
    }


    /**
     * optional string insertion_point = 2;
     * @return {string}
     */
    getInsertionPoint() {
      return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
    }

    /**
     * @param {string} value
     * @return {!proto.google.protobuf.compiler.CodeGeneratorResponse.File} returns this
     */
    setInsertionPoint(value) {
      return jspb.Message.setField(this, 2, value);
    };


    /**
     * Clears the field making it undefined.
     * @return {!proto.google.protobuf.compiler.CodeGeneratorResponse.File} returns this
     */
    clearInsertionPoint() {
      return jspb.Message.setField(this, 2, undefined);
    };


    /**
     * Returns whether this field is set.
     * @return {boolean}
     */
    hasInsertionPoint() {
      return jspb.Message.getField(this, 2) != null;
    }


    /**
     * optional string content = 15;
     * @return {string}
     */
    getContent() {
      return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 15, ""));
    }

    /**
     * @param {string} value
     * @return {!proto.google.protobuf.compiler.CodeGeneratorResponse.File} returns this
     */
    setContent(value) {
      return jspb.Message.setField(this, 15, value);
    };


    /**
     * Clears the field making it undefined.
     * @return {!proto.google.protobuf.compiler.CodeGeneratorResponse.File} returns this
     */
    clearContent() {
      return jspb.Message.setField(this, 15, undefined);
    };


    /**
     * Returns whether this field is set.
     * @return {boolean}
     */
    hasContent() {
      return jspb.Message.getField(this, 15) != null;
    }


    /**
     * optional google.protobuf.GeneratedCodeInfo generated_code_info = 16;
     * @return {?proto.google.protobuf.GeneratedCodeInfo}
     */
    getGeneratedCodeInfo() {
      return /** @type{?proto.google.protobuf.GeneratedCodeInfo} */ (
        jspb.Message.getWrapperField(this, GeneratedCodeInfo, 16));
    }


    /**
     * @param {?proto.google.protobuf.GeneratedCodeInfo|undefined} value
     * @return {!proto.google.protobuf.compiler.CodeGeneratorResponse.File} returns this
    */
    setGeneratedCodeInfo(value) {
      return jspb.Message.setWrapperField(this, 16, value);
    }


    /**
     * Clears the message field making it undefined.
     * @return {!proto.google.protobuf.compiler.CodeGeneratorResponse.File} returns this
     */
    clearGeneratedCodeInfo() {
      return this.setGeneratedCodeInfo(undefined);
    };


    /**
     * Returns whether this field is set.
     * @return {boolean}
     */
    hasGeneratedCodeInfo() {
      return jspb.Message.getField(this, 16) != null;
    }


  } // end class File
  /**
   * optional string error = 1;
   * @return {string}
   */
  getError() {
    return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
  }

  /**
   * @param {string} value
   * @return {!proto.google.protobuf.compiler.CodeGeneratorResponse} returns this
   */
  setError(value) {
    return jspb.Message.setField(this, 1, value);
  };


  /**
   * Clears the field making it undefined.
   * @return {!proto.google.protobuf.compiler.CodeGeneratorResponse} returns this
   */
  clearError() {
    return jspb.Message.setField(this, 1, undefined);
  };


  /**
   * Returns whether this field is set.
   * @return {boolean}
   */
  hasError() {
    return jspb.Message.getField(this, 1) != null;
  }


  /**
   * optional uint64 supported_features = 2;
   * @return {number}
   */
  getSupportedFeatures() {
    return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
  }

  /**
   * @param {number} value
   * @return {!proto.google.protobuf.compiler.CodeGeneratorResponse} returns this
   */
  setSupportedFeatures(value) {
    return jspb.Message.setField(this, 2, value);
  };


  /**
   * Clears the field making it undefined.
   * @return {!proto.google.protobuf.compiler.CodeGeneratorResponse} returns this
   */
  clearSupportedFeatures() {
    return jspb.Message.setField(this, 2, undefined);
  };


  /**
   * Returns whether this field is set.
   * @return {boolean}
   */
  hasSupportedFeatures() {
    return jspb.Message.getField(this, 2) != null;
  }


  /**
   * optional int32 minimum_edition = 3;
   * @return {number}
   */
  getMinimumEdition() {
    return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
  }

  /**
   * @param {number} value
   * @return {!proto.google.protobuf.compiler.CodeGeneratorResponse} returns this
   */
  setMinimumEdition(value) {
    return jspb.Message.setField(this, 3, value);
  };


  /**
   * Clears the field making it undefined.
   * @return {!proto.google.protobuf.compiler.CodeGeneratorResponse} returns this
   */
  clearMinimumEdition() {
    return jspb.Message.setField(this, 3, undefined);
  };


  /**
   * Returns whether this field is set.
   * @return {boolean}
   */
  hasMinimumEdition() {
    return jspb.Message.getField(this, 3) != null;
  }


  /**
   * optional int32 maximum_edition = 4;
   * @return {number}
   */
  getMaximumEdition() {
    return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
  }

  /**
   * @param {number} value
   * @return {!proto.google.protobuf.compiler.CodeGeneratorResponse} returns this
   */
  setMaximumEdition(value) {
    return jspb.Message.setField(this, 4, value);
  };


  /**
   * Clears the field making it undefined.
   * @return {!proto.google.protobuf.compiler.CodeGeneratorResponse} returns this
   */
  clearMaximumEdition() {
    return jspb.Message.setField(this, 4, undefined);
  };


  /**
   * Returns whether this field is set.
   * @return {boolean}
   */
  hasMaximumEdition() {
    return jspb.Message.getField(this, 4) != null;
  }


  /**
   * repeated File file = 15;
   * @return {!Array<!proto.google.protobuf.compiler.CodeGeneratorResponse.File>}
   */
  getFileList() {
    return /** @type{!Array<!proto.google.protobuf.compiler.CodeGeneratorResponse.File>} */ (
      jspb.Message.getRepeatedWrapperField(this, CodeGeneratorResponse.File, 15));
  }


  /**
   * @param {!Array<!proto.google.protobuf.compiler.CodeGeneratorResponse.File>} value
   * @return {!proto.google.protobuf.compiler.CodeGeneratorResponse} returns this
  */
  setFileList(value) {
    return jspb.Message.setRepeatedWrapperField(this, 15, value);
  }


  /**
   * Adds a value to the repeated field fieldName 
   *
   * @param {!proto.google.protobuf.compiler.CodeGeneratorResponse.File=} opt_value
   * @param {number=} opt_index
   * @return {!proto.google.protobuf.compiler.CodeGeneratorResponse.File}
   */
  addFile(opt_value, opt_index) {
    return jspb.Message.addToRepeatedWrapperField(this, 15, opt_value, CodeGeneratorResponse.File, opt_index);
  };


  /**
   * Clears the list making it empty but non-null.
   * @return {!proto.google.protobuf.compiler.CodeGeneratorResponse} returns this
   */
  clearFileList() {
    return this.setFileList([]);
  };


} // end class CodeGeneratorResponse
